/* defgodqe — mega experience layer */
(()=>{
'use strict';
if(window.__defgodqeMega)return;window.__defgodqeMega=true;
const KEY='defgodqe-mega-prefs-v1';
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}};
const write=x=>{try{localStorage.setItem(KEY,JSON.stringify(x))}catch{}};
let prefs=read();
const toast=(t)=>{let e=document.getElementById('dfMegaToast');if(!e){e=document.createElement('div');e.id='dfMegaToast';document.body.appendChild(e)}e.textContent=t;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),1700)};
function css(){if(document.getElementById('dfMegaStyle'))return;const s=document.createElement('style');s.id='dfMegaStyle';s.textContent=`
#dfMega{position:fixed;inset:0;z-index:100500;display:none;background:rgba(3,5,9,.78);backdrop-filter:blur(18px);align-items:center;justify-content:center;padding:18px}#dfMega.open{display:flex}.dfm-box{width:min(760px,100%);max-height:min(720px,90vh);overflow:auto;background:linear-gradient(145deg,#111722,#090d14);border:1px solid rgba(255,255,255,.1);border-radius:28px;box-shadow:0 35px 120px #000;padding:22px}.dfm-head{display:flex;align-items:center;gap:12px}.dfm-head h2{margin:0;font-size:25px}.dfm-sub{color:#8995a8;font-size:13px;margin:4px 0 18px}.dfm-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.dfm-card{border:1px solid rgba(255,255,255,.08);background:rgba(255,255,255,.045);border-radius:18px;padding:15px;color:#fff;text-align:left;cursor:pointer;transition:.18s}.dfm-card:hover{transform:translateY(-2px);background:rgba(255,255,255,.08);border-color:rgba(250,204,21,.35)}.dfm-card b{display:block;font-size:14px}.dfm-card span{display:block;color:#8995a8;font-size:12px;margin-top:4px}.dfm-icon{font-size:21px;margin-bottom:8px}.dfm-close{margin-left:auto;border:0;background:rgba(255,255,255,.07);color:#fff;width:40px;height:40px;border-radius:12px;font-size:20px;cursor:pointer}.dfm-row{display:flex;gap:8px;flex-wrap:wrap;margin-top:18px}.dfm-btn{border:1px solid rgba(255,255,255,.1);background:#171d28;color:#fff;border-radius:12px;padding:10px 13px;font-weight:800;cursor:pointer}.dfm-btn.primary{background:#facc15;color:#111;border-color:#facc15}.dfm-search{width:100%;margin:12px 0 14px;background:#080b11;border:1px solid rgba(255,255,255,.1);color:#fff;border-radius:14px;padding:13px;outline:0}.dfm-search:focus{border-color:rgba(250,204,21,.5)}#dfMegaToast{position:fixed;left:50%;bottom:28px;transform:translate(-50%,15px);z-index:100600;background:#111722;color:#fff;border:1px solid rgba(255,255,255,.14);border-radius:14px;padding:11px 16px;font-weight:800;opacity:0;pointer-events:none;transition:.2s;box-shadow:0 15px 50px #000}#dfMegaToast.show{opacity:1;transform:translate(-50%,0)}.dfm-command{position:fixed;right:18px;bottom:18px;z-index:100490;border:1px solid rgba(255,255,255,.12);background:rgba(15,19,28,.86);backdrop-filter:blur(15px);color:#fff;border-radius:14px;padding:9px 12px;font-size:12px;font-weight:800;cursor:pointer}@media(max-width:650px){.dfm-grid{grid-template-columns:1fr}.dfm-box{padding:16px;border-radius:22px}.dfm-command{right:10px;bottom:10px}}
body.dfm-focus #sidebar,body.dfm-focus header{filter:brightness(.65)}body.dfm-focus #scroll{max-width:980px;margin:auto;width:100%}
` ;document.head.appendChild(s)}
function open(){css();let root=document.getElementById('dfMega');if(!root){root=document.createElement('div');root.id='dfMega';root.innerHTML=`<div class="dfm-box" role="dialog" aria-modal="true"><div class="dfm-head"><div><h2>defgodqe control center</h2><div class="dfm-sub">One place for your AI, productivity, appearance and shortcuts.</div></div><button class="dfm-close" id="dfmClose">×</button></div><input id="dfmSearch" class="dfm-search" placeholder="Search features…" autocomplete="off"><div class="dfm-grid" id="dfmGrid"></div><div class="dfm-row"><button class="dfm-btn" data-action="focus">⛶ Focus mode</button><button class="dfm-btn" data-action="theme">◐ Contrast</button><button class="dfm-btn" data-action="top">↑ Top</button><button class="dfm-btn primary" data-action="new">＋ New chat</button></div></div>`;document.body.appendChild(root);root.querySelector('#dfmClose').onclick=()=>root.classList.remove('open');root.addEventListener('click',e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(!a)return;if(a==='focus'){document.body.classList.toggle('dfm-focus');toast(document.body.classList.contains('dfm-focus')?'Focus mode on':'Focus mode off')}if(a==='theme'){document.documentElement.classList.toggle('dfm-high-contrast');toast('Contrast toggled')}if(a==='top'){document.getElementById('scroll')?.scrollTo({top:0,behavior:'smooth'});toast('Back to top')}if(a==='new'){document.getElementById('newChatBtn')?.click();root.classList.remove('open')}});root.querySelector('#dfmSearch').addEventListener('input',render);}
const items=[['🤖','AI chat','Open your main assistant'],['🎮','Mini games','Launch the game center'],['🎬','Doom scroll','Open the creator video feed'],['⚡','Quick new chat','Start a fresh conversation'],['🎙️','Voice','Open voice mode'],['🌐','Web search','Toggle web-powered answers'],['📱','Install app','Install defgodqe when available'],['⌨️','Shortcuts','View keyboard shortcuts']];
function render(){const q=(document.getElementById('dfmSearch')?.value||'').toLowerCase();const g=document.getElementById('dfmGrid');if(!g)return;g.innerHTML=items.filter(x=>(x[1]+' '+x[2]).toLowerCase().includes(q)).map(x=>`<button class="dfm-card" data-feature="${x[1]}"><div class="dfm-icon">${x[0]}</div><b>${x[1]}</b><span>${x[2]}</span></button>`).join('');g.querySelectorAll('.dfm-card').forEach(b=>b.onclick=()=>run(b.dataset.feature))}
function run(name){const map={'AI chat':()=>document.getElementById('input')?.focus(),'Mini games':()=>document.querySelector('#miniGameBtn,#gameBtn,[data-mini-games]')?.click(),'Doom scroll':()=>window.defgodqeOwnedDoomOpen?.(),'Quick new chat':()=>document.getElementById('newChatBtn')?.click(),'Voice':()=>document.getElementById('voiceBtn')?.click(),'Web search':()=>document.getElementById('webBtn')?.click(),'Install app':()=>window.dispatchEvent(new Event('beforeinstallprompt')),'Shortcuts':()=>toast('Ctrl/Cmd+K center • Ctrl/Cmd+Shift+O Doom • Ctrl/Cmd+Shift+N New chat')};try{map[name]?.();if(name!=='Shortcuts')document.getElementById('dfMega')?.classList.remove('open')}catch(e){toast('That feature is not ready yet')}}
function boot(){css();const b=document.createElement('button');b.className='dfm-command';b.textContent='⌘ Control';b.title='Open defgodqe control center';b.onclick=open;document.body.appendChild(b);document.addEventListener('keydown',e=>{const mod=e.ctrlKey||e.metaKey;if(mod&&e.key.toLowerCase()==='k'){e.preventDefault();open()}if(mod&&e.shiftKey&&e.key.toLowerCase()==='o'){e.preventDefault();window.defgodqeOwnedDoomOpen?.()}if(mod&&e.shiftKey&&e.key.toLowerCase()==='n'){e.preventDefault();document.getElementById('newChatBtn')?.click()}if(e.key==='Escape')document.getElementById('dfMega')?.classList.remove('open')});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
window.defgodqeMega={open,toast};
})();