/* defgodqe — advanced direct messaging upgrade
 * Adds 1-on-1 + group chats, video sharing, read receipts, unread badges,
 * typing indicators, conversation search, and a polished messenger UI.
 */
(() => {
  const KEY='defgodqe-dm-v2', USER_KEY='defgodqe-social-user';
  const uid=()=>crypto.randomUUID?.()||`dm-${Date.now()}-${Math.random().toString(36).slice(2)}`;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const me=()=>{try{return JSON.parse(localStorage.getItem(USER_KEY)||'null')}catch{return null}};
  const get=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{"chats":{},"typing":{}}')}catch{return {chats:{},typing:{}}}};
  const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
  const name=()=>me()?.username||'guest', id=()=>me()?.id||'guest';
  let active=null, timer=null;
  function ensure(s,key,participants=[],title=''){
    s.chats[key] ||= {id:key,type:participants.length>2?'group':'direct',title,participants,messages:[],createdAt:Date.now()};
    return s.chats[key];
  }
  function chatKey(ids){return [...new Set(ids)].sort().join('|')}
  function inject(){if(document.getElementById('dfDmStyles'))return;const x=document.createElement('style');x.id='dfDmStyles';x.textContent=`
#dfDm{position:fixed;inset:0;z-index:100001;display:none;background:#070912;color:#fff;font-family:system-ui,-apple-system,sans-serif}#dfDm.open{display:flex}.dfdm-shell{display:grid;grid-template-columns:330px 1fr;width:100%;height:100%}.dfdm-side{border-right:1px solid #ffffff14;background:#0b0e18;overflow:auto}.dfdm-head{padding:18px;border-bottom:1px solid #ffffff12}.dfdm-title{font-size:22px;font-weight:800}.dfdm-search{width:100%;box-sizing:border-box;margin-top:12px;padding:11px 13px;border-radius:13px;border:1px solid #ffffff15;background:#ffffff08;color:#fff;outline:none}.dfdm-list{padding:8px}.dfdm-chat{display:flex;gap:10px;padding:12px;border-radius:14px;cursor:pointer;align-items:center}.dfdm-chat:hover,.dfdm-chat.active{background:#ffffff0d}.dfdm-avatar{width:42px;height:42px;border-radius:50%;background:linear-gradient(135deg,#252b42,#111522);display:grid;place-items:center;font-weight:800;flex:none}.dfdm-meta{min-width:0;flex:1}.dfdm-meta b,.dfdm-meta span{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.dfdm-meta span{opacity:.58;font-size:13px;margin-top:3px}.dfdm-unread{min-width:20px;height:20px;padding:0 5px;border-radius:999px;background:#fff;color:#000;font-size:11px;display:grid;place-items:center;font-weight:800}.dfdm-main{display:flex;flex-direction:column;min-width:0}.dfdm-bar{padding:15px 18px;border-bottom:1px solid #ffffff12;display:flex;align-items:center;gap:12px}.dfdm-bar b{font-size:16px}.dfdm-close{margin-left:auto}.dfdm-icon{border:1px solid #ffffff15;background:#ffffff08;color:#fff;border-radius:11px;padding:9px 11px;cursor:pointer}.dfdm-messages{flex:1;overflow:auto;padding:20px;display:flex;flex-direction:column;gap:7px}.dfdm-msg{max-width:min(72%,560px);padding:10px 13px;border-radius:17px;background:#ffffff0d;align-self:flex-start}.dfdm-msg.mine{background:#fff;color:#000;align-self:flex-end}.dfdm-msg small{display:block;opacity:.5;font-size:10px;margin-top:5px}.dfdm-video{display:block;max-width:290px;max-height:380px;border-radius:13px;margin-bottom:5px;background:#000}.dfdm-composer{border-top:1px solid #ffffff12;padding:12px;display:flex;gap:8px;align-items:flex-end}.dfdm-input{flex:1;min-height:44px;max-height:130px;resize:none;border:1px solid #ffffff15;background:#ffffff08;color:#fff;border-radius:15px;padding:12px;box-sizing:border-box;outline:none}.dfdm-send{background:#fff;color:#000;border:0;border-radius:14px;padding:12px 17px;font-weight:800;cursor:pointer}.dfdm-typing{height:20px;padding:0 20px;opacity:.6;font-size:12px}.dfdm-empty{margin:auto;text-align:center;opacity:.55}.dfdm-new{margin-top:10px;width:100%}.dfdm-back{display:none}@media(max-width:720px){.dfdm-shell{grid-template-columns:1fr}.dfdm-side{display:none}.dfdm-shell.list .dfdm-side{display:block}.dfdm-shell.list .dfdm-main{display:none}.dfdm-back{display:inline-block}.dfdm-msg{max-width:84%}}
`;document.head.appendChild(x)}
  function users(){const p=JSON.parse(localStorage.getItem('defgodqe-social-platform-v1')||'{"users":{}}');return Object.values(p.users||{}).filter(u=>u.id!==id())}
  function open(){inject();let root=document.getElementById('dfDm');if(!root){root=document.createElement('div');root.id='dfDm';document.body.appendChild(root)}root.classList.add('open');render();}
  function close(){document.getElementById('dfDm')?.classList.remove('open');clearInterval(timer);timer=null}
  function render(){const s=get(), chats=Object.values(s.chats).filter(c=>c.participants.includes(id()));const root=document.getElementById('dfDm');root.innerHTML=`<div class="dfdm-shell" id="dfdmShell"><aside class="dfdm-side"><div class="dfdm-head"><div class="dfdm-title">Messages</div><button class="dfdm-icon dfdm-new" id="dfDmNew">＋ New chat</button><input class="dfdm-search" id="dfDmSearch" placeholder="Search messages"></div><div class="dfdm-list" id="dfDmList"></div></aside><section class="dfdm-main"><header class="dfdm-bar"><button class="dfdm-icon dfdm-back" id="dfDmBack">←</button><div id="dfDmTitle"><b>Choose a conversation</b></div><button class="dfdm-icon dfdm-close" id="dfDmClose">✕</button></header><div class="dfdm-messages" id="dfDmMessages"><div class="dfdm-empty">Select a chat to start messaging.</div></div><div class="dfdm-typing" id="dfDmTyping"></div><footer class="dfdm-composer"><input type="file" id="dfDmVideo" accept="video/*" hidden><button class="dfdm-icon" id="dfDmAttach" title="Send video">🎬</button><textarea class="dfdm-input" id="dfDmInput" placeholder="Message…" rows="1"></textarea><button class="dfdm-send" id="dfDmSend">Send</button></footer></section></div>`;
    const list=root.querySelector('#dfDmList');const q='';list.innerHTML=chats.map(c=>row(c)).join('')||'<div class="dfdm-empty" style="padding:25px">No conversations yet.</div>';chats.forEach(c=>list.querySelector(`[data-chat="${CSS.escape(c.id)}"]`)?.addEventListener('click',()=>select(c.id)));root.querySelector('#dfDmClose').onclick=close;root.querySelector('#dfDmNew').onclick=newChat;root.querySelector('#dfDmBack').onclick=()=>root.querySelector('#dfdmShell').classList.add('list');root.querySelector('#dfDmSearch').oninput=e=>filter(e.target.value);root.querySelector('#dfDmSend').onclick=send;root.querySelector('#dfDmAttach').onclick=()=>root.querySelector('#dfDmVideo').click();root.querySelector('#dfDmVideo').onchange=e=>{const f=e.target.files?.[0];if(f)sendVideo(f)};const input=root.querySelector('#dfDmInput');input.oninput=()=>typing(true);input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}else typing(true)};if(active&&s.chats[active])select(active);}
  function row(c){const unread=(c.messages||[]).filter(m=>m.to===id()&&!m.read).length;const last=c.messages?.[c.messages.length-1];const label=c.type==='group'?(c.title||'Group chat'):((users().find(u=>u.id!==id()&&c.participants.includes(u.id))?.username)||'Conversation');return `<div class="dfdm-chat ${active===c.id?'active':''}" data-chat="${esc(c.id)}"><div class="dfdm-avatar">${esc(label[0]?.toUpperCase()||'?')}</div><div class="dfdm-meta"><b>@${esc(label)}</b><span>${esc(last?.type==='video'?'🎬 Video':last?.text||'New conversation')}</span></div>${unread?`<span class="dfdm-unread">${unread>99?'99+':unread}</span>`:''}</div>`}
  function select(key){active=key;const s=get(),c=s.chats[key];if(!c)return;document.getElementById('dfdmShell')?.classList.remove('list');c.messages.forEach(m=>{if(m.to===id())m.read=true});save(s);const label=c.type==='group'?(c.title||'Group chat'):((users().find(u=>u.id!==id()&&c.participants.includes(u.id))?.username)||'Conversation');document.getElementById('dfDmTitle').innerHTML=`<b>${esc(label)}</b><span style="opacity:.5;font-size:12px;margin-left:8px">${c.type==='group'?`${c.participants.length} members`:'Direct message'}</span>`;const box=document.getElementById('dfDmMessages');box.innerHTML=c.messages.map(m=>`<div class="dfdm-msg ${m.from===id()?'mine':''}">${m.type==='video'?`<video class="dfdm-video" src="${esc(m.url)}" controls playsinline preload="metadata"></video>`:esc(m.text)}<small>${m.from===id()?(m.read?'✓✓ Read':'✓ Sent'):esc(m.username||'')} · ${new Date(m.createdAt).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</small></div>`).join('')||'<div class="dfdm-empty">Say hello 👋</div>';box.scrollTop=box.scrollHeight;renderListOnly();}
  function renderListOnly(){const s=get(),list=document.getElementById('dfDmList');if(list)list.innerHTML=Object.values(s.chats).filter(c=>c.participants.includes(id())).map(row).join('');list?.querySelectorAll('[data-chat]').forEach(x=>x.onclick=()=>select(x.dataset.chat));}
  function filter(q){const s=get(),list=document.getElementById('dfDmList'),x=q.toLowerCase();list.innerHTML=Object.values(s.chats).filter(c=>c.participants.includes(id())&&c.messages.some(m=>(m.text||'').toLowerCase().includes(x))).map(row).join('')||'<div class="dfdm-empty" style="padding:25px">No matching messages.</div>';list.querySelectorAll('[data-chat]').forEach(b=>b.onclick=()=>select(b.dataset.chat));}
  function newChat(){const all=users();const raw=prompt('Enter username(s), separated by commas. Use more than one for a group chat:');if(!raw)return;const names=raw.split(',').map(x=>x.trim().toLowerCase()).filter(Boolean);const picked=all.filter(u=>names.includes((u.username||'').toLowerCase()));if(!picked.length){alert('No matching users found.');return}const key=chatKey([id(),...picked.map(u=>u.id)]),s=get(),c=ensure(s,key,[id(),...picked.map(u=>u.id)],picked.length>1?'New group chat':'');save(s);active=c.id;render();}
  function send(){const input=document.getElementById('dfDmInput'),text=input?.value.trim();if(!text||!active)return;const s=get(),c=s.chats[active];c.messages.push({id:uid(),from:id(),to:c.participants.find(x=>x!==id())||null,username:name(),text,read:false,createdAt:Date.now()});save(s);input.value='';typing(false);select(active);}
  function sendVideo(file){if(!active)return;const s=get(),c=s.chats[active];if(file.size>100*1024*1024){alert('Video must be 100MB or smaller.');return}const url=URL.createObjectURL(file);c.messages.push({id:uid(),from:id(),to:c.participants.find(x=>x!==id())||null,username:name(),type:'video',url,fileName:file.name,read:false,createdAt:Date.now()});save(s);select(active);}
  function typing(on){if(!active)return;const s=get();s.typing[active]={user:id(),username:name(),until:on?Date.now()+1800:0};save(s);const out=document.getElementById('dfDmTyping');if(out)out.textContent=on?'Typing…':'';clearTimeout(timer);if(on)timer=setTimeout(()=>typing(false),1700)}
  function tick(){if(!active)return;const s=get(),t=s.typing[active];const out=document.getElementById('dfDmTyping');if(out)out.textContent=t&&t.user!==id()&&t.until>Date.now()?`@${t.username} is typing…`:''}
  window.defgodqeDM={open,close,newChat,sendVideo};
  document.addEventListener('click',e=>{if(e.target.closest('#messagesBtn,[data-messages],[data-open-messages]')){e.preventDefault();open()}},true);
  window.addEventListener('defgodqe-auth-changed',()=>{if(document.getElementById('dfDm.open'))render()});
  setInterval(tick,350);
})();
