/* defgodqe — Owned Doom Feed
 * A first-party short-video surface: vertical snap feed, creator uploads,
 * likes/follows, share, explore tabs, local fallback, and optional social API.
 */
(function(){
'use strict';
if(window.__defgodqeOwnedDoom)return;
window.__defgodqeOwnedDoom=true;
const API=(window.DEFGODQE_SOCIAL_API||'').replace(/\/$/,'');
const LOCAL='defgodqe-owned-feed-v1', USER='defgodqe-social-user', DEVICE='defgodqe-social-device-id';
let me=null, posts=[], mode='for-you', open=false, active=0, observer=null;
try{me=JSON.parse(localStorage.getItem(USER)||'null')}catch{}
const load=()=>{try{const x=JSON.parse(localStorage.getItem(LOCAL)||'[]');return Array.isArray(x)?x:[]}catch{return[]}};
const save=x=>{try{localStorage.setItem(LOCAL,JSON.stringify(x))}catch{}};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const headers=()=>({'x-user-id':localStorage.getItem(DEVICE)||'owned-'+Date.now()});
async function api(path,opts={}){if(!API)throw Error('Social API is not configured');const h={...headers(),...(opts.headers||{})};if(opts.body&&!(opts.body instanceof FormData))h['content-type']='application/json';const r=await fetch(API+path,{...opts,headers:h});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`Request failed (${r.status})`);return d}
const style=document.createElement('style');style.textContent=`
#dfOwned{position:fixed;inset:0;z-index:100030;background:#050505;color:#fff;display:none;font-family:Inter,system-ui,sans-serif}#dfOwned.open{display:block}
#dfOwnedFeed{position:absolute;inset:0;overflow-y:auto;scroll-snap-type:y mandatory;scrollbar-width:none;overscroll-behavior:contain}#dfOwnedFeed::-webkit-scrollbar{display:none}
.df-o-card{height:100dvh;min-height:520px;scroll-snap-align:start;position:relative;background:#000;display:flex;justify-content:center;overflow:hidden}.df-o-video{width:min(100vw,56.25dvh);height:100%;object-fit:cover;background:#090909}.df-o-shade{position:absolute;inset:0;pointer-events:none;background:linear-gradient(transparent 42%,rgba(0,0,0,.12) 55%,rgba(0,0,0,.88) 100%)}
.df-o-top{position:fixed;z-index:4;top:0;left:0;right:0;height:68px;display:flex;align-items:center;gap:8px;padding:0 14px;background:linear-gradient(rgba(0,0,0,.7),transparent);pointer-events:none}.df-o-top>*{pointer-events:auto}.df-o-brand{font-weight:950;font-size:20px;margin-right:auto}.df-o-brand span{opacity:.5;font-weight:600}.df-o-tab{border:0;background:rgba(20,20,24,.7);backdrop-filter:blur(12px);color:#aaa;padding:9px 13px;border-radius:14px;font-weight:800;cursor:pointer}.df-o-tab.active{color:#fff;background:rgba(255,255,255,.14)}.df-o-top button{border:1px solid rgba(255,255,255,.14);color:#fff;background:rgba(15,15,18,.72);border-radius:13px;padding:9px 12px;cursor:pointer;font-weight:800}
.df-o-info{position:absolute;left:max(16px,calc(50% - min(28.125dvh,50vw) + 16px));right:82px;bottom:25px;z-index:2}.df-o-user{display:flex;align-items:center;gap:10px;font-weight:900}.df-o-avatar{width:42px;height:42px;border-radius:50%;display:grid;place-items:center;background:linear-gradient(135deg,#fff,#666);color:#000;font-weight:950}.df-o-follow{border:1px solid rgba(255,255,255,.35);background:rgba(255,255,255,.1);color:#fff;border-radius:10px;padding:7px 10px;font-weight:800;cursor:pointer}.df-o-title{font-size:16px;font-weight:650;line-height:1.35;margin-top:9px}.df-o-tags{color:#ddd;font-size:13px;margin-top:7px}.df-o-actions{position:absolute;right:max(12px,calc(50% - min(28.125dvh,50vw) + 12px));bottom:30px;z-index:3;display:flex;flex-direction:column;gap:13px}.df-o-act{width:48px;height:48px;border:0;border-radius:50%;background:rgba(15,15,18,.68);backdrop-filter:blur(10px);color:#fff;font-size:21px;cursor:pointer;display:grid;place-items:center}.df-o-act small{font-size:10px;font-weight:900;margin-top:-4px}.df-o-act.liked{background:#fff;color:#000}.df-o-close{position:fixed;top:14px;right:14px;z-index:8;width:42px;height:42px;border-radius:50%;border:1px solid rgba(255,255,255,.2);background:rgba(0,0,0,.55);color:#fff;font-size:25px;cursor:pointer}.df-o-empty{height:100%;display:grid;place-items:center;text-align:center;padding:30px;color:#fff}.df-o-empty div{max-width:420px}.df-o-empty h2{font-size:30px;margin:0 0 8px}.df-o-empty p{color:#aaa}.df-o-modal{position:fixed;inset:0;background:rgba(0,0,0,.76);z-index:10;display:none;align-items:center;justify-content:center;padding:18px}.df-o-modal.open{display:flex}.df-o-box{width:min(520px,100%);background:#111116;border:1px solid rgba(255,255,255,.12);border-radius:24px;padding:20px;box-shadow:0 20px 80px #000}.df-o-box h2{margin:0 0 5px}.df-o-muted{color:#999;font-size:13px}.df-o-input{width:100%;box-sizing:border-box;margin-top:10px;background:#08080b;border:1px solid rgba(255,255,255,.13);color:#fff;border-radius:13px;padding:12px}.df-o-row{display:flex;gap:8px;justify-content:flex-end;margin-top:14px}.df-o-btn{border:1px solid rgba(255,255,255,.14);background:#1b1b22;color:#fff;border-radius:12px;padding:10px 14px;font-weight:800;cursor:pointer}.df-o-btn.primary{background:#fff;color:#000}
@media(max-width:650px){.df-o-top{height:58px;padding:0 9px}.df-o-brand{font-size:17px}.df-o-tab{padding:8px 9px;font-size:12px}.df-o-top button{padding:8px 9px}.df-o-info{left:14px;right:74px;bottom:20px}.df-o-actions{right:10px;bottom:22px}.df-o-video{width:100vw}.df-o-close{top:10px;right:8px}}
`;document.head.appendChild(style);
const root=document.createElement('div');root.id='dfOwned';root.innerHTML=`<div class="df-o-top"><div class="df-o-brand">defgodqe <span>doom</span></div><button class="df-o-tab active" data-mode="for-you">For You</button><button class="df-o-tab" data-mode="following">Following</button><button class="df-o-tab" data-mode="explore">Explore</button><button id="dfOUpload">＋ Post</button></div><div id="dfOwnedFeed"></div><button class="df-o-close" id="dfOClose">×</button><div class="df-o-modal" id="dfOModal"><div class="df-o-box"><h2>Create a post</h2><div class="df-o-muted">Upload a video you own or have permission to share.</div><input class="df-o-input" id="dfOFile" type="file" accept="video/mp4,video/webm,video/quicktime"><input class="df-o-input" id="dfOTitle" maxlength="120" placeholder="What's happening? Caption / title"><input class="df-o-input" id="dfOTags" maxlength="240" placeholder="Tags — gaming, minecraft, funny"><div class="df-o-row"><button class="df-o-btn" id="dfOCancel">Cancel</button><button class="df-o-btn primary" id="dfOPost">Publish</button></div></div></div></div>`;document.body.appendChild(root);
const feed=root.querySelector('#dfOwnedFeed'),modal=root.querySelector('#dfOModal');
function normalize(v,i){return{id:v.id||v.video_id||('local-'+i),url:v.url||v.video_url,title:v.title||v.caption||'New defgodqe short',user:v.user||v.username||'creator',userId:v.userId||v.user_id||'',likes:Number(v.likes||0),liked:!!v.liked,tags:v.tags||'',provider:'defgodqe'}}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
async function loadPosts(){
 let remote=[];
 if(API){try{const d=await api('/api/feed');remote=(d.videos||[]).map(normalize)}catch(e){console.warn('defgodqe social feed:',e)}}
 const local=load().map(normalize).filter(x=>x.url);
 const seen=new Set();posts=[...remote,...local].filter(x=>{if(!x.url||seen.has(x.id))return false;seen.add(x.id);return true});
 if(mode==='following')posts=posts.filter(x=>x.following||x.userId&&x.following===true);
 posts=shuffle(posts);
}
function card(v,i){return `<section class="df-o-card" data-i="${i}"><video class="df-o-video" src="${esc(v.url)}" playsinline loop preload="metadata"></video><div class="df-o-shade"></div><div class="df-o-info"><div class="df-o-user"><div class="df-o-avatar">${esc((v.user||'c')[0].toUpperCase())}</div><span>@${esc(v.user)}</span>${v.userId?`<button class="df-o-follow" data-follow="${esc(v.userId)}">Follow</button>`:''}</div><div class="df-o-title">${esc(v.title)}</div>${v.tags?`<div class="df-o-tags">${esc(v.tags)}</div>`:''}</div><div class="df-o-actions"><button class="df-o-act ${v.liked?'liked':''}" data-like="${esc(v.id)}">♥<small>${v.likes}</small></button><button class="df-o-act" data-comment="${esc(v.id)}">💬<small>Comment</small></button><button class="df-o-act" data-share="${esc(v.url)}">↗<small>Share</small></button></div></section>`}
function render(){feed.innerHTML=posts.length?posts.map(card).join(''):`<div class="df-o-empty"><div><h2>Welcome to defgodqe Doom</h2><p>This is your first-party creator feed. Post your own videos and build the community here.</p><button class="df-o-btn primary" id="dfOEmptyPost">＋ Publish your first short</button></div></div>`;root.querySelector('#dfOEmptyPost')?.addEventListener('click',openUpload);setupObserver();playActive(0)}
function playActive(i){const cards=[...feed.querySelectorAll('.df-o-card')];cards.forEach((c,n)=>{const v=c.querySelector('video');if(n===i){v.currentTime=0;v.muted=false;v.play().catch(()=>{v.muted=true;v.play().catch(()=>{})})}else{v.pause();v.currentTime=0;v.muted=true}});active=i}
function setupObserver(){observer?.disconnect();const cards=[...feed.querySelectorAll('.df-o-card')];if(!cards.length)return;observer=new IntersectionObserver(es=>{const best=es.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(best){const i=Number(best.target.dataset.i);if(i!==active)playActive(i)}},{root:feed,threshold:[.65,.85]});cards.forEach(c=>observer.observe(c))}
async function openOwned(){open=true;root.classList.add('open');document.body.style.overflow='hidden';await loadPosts();render()}
function closeOwned(){open=false;observer?.disconnect();root.querySelectorAll('video').forEach(v=>{v.pause();v.currentTime=0});root.classList.remove('open');document.body.style.overflow=''}
function openUpload(){if(!API&&!me){const username=prompt('Choose your defgodqe username:','creator');if(username){me={username};localStorage.setItem(USER,JSON.stringify(me))}}modal.classList.add('open')}
root.querySelector('#dfOClose').onclick=closeOwned;root.querySelector('#dfOUpload').onclick=openUpload;root.querySelector('#dfOCancel').onclick=()=>modal.classList.remove('open');root.querySelectorAll('[data-mode]').forEach(b=>b.onclick=async()=>{mode=b.dataset.mode;root.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));await loadPosts();render()});
root.querySelector('#dfOPost').onclick=async()=>{const file=root.querySelector('#dfOFile').files[0];if(!file)return alert('Choose a video first.');if(file.size>100*1024*1024)return alert('Maximum video size is 100 MB.');const title=root.querySelector('#dfOTitle').value.trim()||'New defgodqe short';const tags=root.querySelector('#dfOTags').value.trim();const btn=root.querySelector('#dfOPost');btn.disabled=true;try{if(API){if(!me){const username=prompt('Choose your defgodqe username:','creator');if(!username)throw Error('Username required');me=await api('/api/users',{method:'POST',body:JSON.stringify({username})});localStorage.setItem(USER,JSON.stringify(me))}const fd=new FormData();fd.append('file',file);fd.append('title',title);fd.append('tags',tags);await api('/api/videos',{method:'POST',body:fd});}else{const url=URL.createObjectURL(file);const item={id:'local-'+Date.now(),url,title,user:me?.username||'you',userId:'local',likes:0,tags};const arr=load();arr.unshift(item);save(arr)}modal.classList.remove('open');await loadPosts();render()}catch(e){alert(e.message)}finally{btn.disabled=false}};
root.addEventListener('click',async e=>{const like=e.target.closest('[data-like]');if(like){const p=posts.find(x=>String(x.id)===String(like.dataset.like));if(!p)return;try{if(API)await api('/api/videos/'+encodeURIComponent(p.id)+'/like',{method:'POST'});p.liked=!p.liked;p.likes=Math.max(0,p.likes+(p.liked?1:-1));like.classList.toggle('liked',p.liked);like.innerHTML=`♥<small>${p.likes}</small>`}catch(err){alert(err.message)}}const share=e.target.closest('[data-share]');if(share){try{await navigator.clipboard?.writeText(share.dataset.share);alert('Video link copied.')}catch{alert(share.dataset.share)}}const comment=e.target.closest('[data-comment]');if(comment){const text=prompt('Comment on this short:');if(text?.trim())alert('Comment saved for this post in the next social-backend upgrade.')}});
window.defgodqeOwnedDoomOpen=openOwned;window.defgodqeOwnedDoomClose=closeOwned;
function hookButton(){const b=document.getElementById('dfDoomBtn');if(!b)return false;b.onclick=openOwned;const label=b.querySelector('span:nth-child(2)');if(label)label.textContent='Doom scroll';const badge=b.querySelector('span:last-child');if(badge)badge.textContent='DEFGODQE';return true}
if(!hookButton()){const mo=new MutationObserver(()=>{if(hookButton())mo.disconnect()});mo.observe(document.body,{childList:true,subtree:true})}
})();
