/* defgodqe — Doom Social: TikTok-style home, creator tools, profiles and messaging */
(function(){
'use strict';
if(window.__defgodqeDoomSocial)return;
window.__defgodqeDoomSocial=true;

const KEY='defgodqe-doom-social-v1';
const state={videos:[],messages:{},following:[],liked:[]};
try{Object.assign(state,JSON.parse(localStorage.getItem(KEY)||'{}'))}catch(_){}
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(state))}catch(_) {}};

const style=document.createElement('style');style.textContent=`
#dfSocial{position:fixed;inset:0;z-index:100010;background:#050507;color:#fff;display:none;font-family:Inter,system-ui,sans-serif;overflow:hidden}
#dfSocial.open{display:block}
.df-s-head{height:64px;display:flex;align-items:center;gap:14px;padding:0 18px;border-bottom:1px solid rgba(255,255,255,.08);background:rgba(8,8,12,.9);backdrop-filter:blur(18px);position:relative;z-index:3}
.df-s-logo{font-weight:900;font-size:20px;letter-spacing:-.5px}.df-s-logo span{opacity:.45;font-weight:600}
.df-s-tabs{display:flex;gap:4px;margin:auto}.df-s-tab,.df-s-icon{border:0;background:transparent;color:#aaa;padding:10px 13px;border-radius:12px;cursor:pointer;font-weight:700}.df-s-tab.active,.df-s-tab:hover,.df-s-icon:hover{background:rgba(255,255,255,.08);color:#fff}
.df-s-main{height:calc(100% - 64px);overflow:auto}.df-s-page{max-width:1100px;margin:auto;padding:22px}.df-s-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:14px}.df-s-card{background:#111116;border:1px solid rgba(255,255,255,.08);border-radius:18px;overflow:hidden}.df-s-thumb{height:300px;background:linear-gradient(145deg,#171722,#09090d);display:flex;align-items:center;justify-content:center;color:#777}.df-s-card video{width:100%;height:300px;object-fit:cover;display:block}.df-s-info{padding:12px}.df-s-row{display:flex;align-items:center;gap:9px}.df-s-avatar{width:34px;height:34px;border-radius:50%;background:linear-gradient(135deg,#fff,#555);color:#000;display:grid;place-items:center;font-weight:900}.df-s-muted{color:#888;font-size:13px}.df-s-btn{border:1px solid rgba(255,255,255,.12);background:#17171e;color:#fff;border-radius:11px;padding:9px 12px;cursor:pointer;font-weight:700}.df-s-btn.primary{background:#fff;color:#000}.df-s-btn:hover{filter:brightness(1.12)}
.df-s-compose{padding:18px;border:1px solid rgba(255,255,255,.09);border-radius:20px;background:#101015;margin-bottom:18px}.df-s-drop{border:1px dashed rgba(255,255,255,.2);border-radius:16px;padding:32px;text-align:center;cursor:pointer}.df-s-drop:hover{background:rgba(255,255,255,.03)}
.df-s-chat{display:grid;grid-template-columns:280px 1fr;height:calc(100vh - 110px);border:1px solid rgba(255,255,255,.08);border-radius:18px;overflow:hidden}.df-s-users{border-right:1px solid rgba(255,255,255,.08);overflow:auto}.df-s-user{padding:14px;display:flex;gap:10px;align-items:center;cursor:pointer}.df-s-user:hover,.df-s-user.sel{background:rgba(255,255,255,.06)}.df-s-convo{display:flex;flex-direction:column;min-width:0}.df-s-msgs{flex:1;overflow:auto;padding:18px}.df-s-bubble{max-width:70%;padding:10px 13px;border-radius:15px;background:#181820;margin:7px 0}.df-s-bubble.me{margin-left:auto;background:#fff;color:#000}.df-s-send{display:flex;gap:8px;padding:12px;border-top:1px solid rgba(255,255,255,.08)}.df-s-send input{flex:1;background:#111118;border:1px solid rgba(255,255,255,.12);color:#fff;border-radius:12px;padding:12px;outline:0}
.df-s-modal{position:fixed;inset:0;background:rgba(0,0,0,.7);display:none;align-items:center;justify-content:center;z-index:100020;padding:20px}.df-s-modal.open{display:flex}.df-s-box{width:min(520px,100%);background:#101015;border:1px solid rgba(255,255,255,.12);border-radius:20px;padding:20px}.df-s-box input,.df-s-box textarea{width:100%;box-sizing:border-box;background:#0b0b10;color:#fff;border:1px solid rgba(255,255,255,.12);border-radius:12px;padding:12px;margin:7px 0 12px;outline:0}
@media(max-width:700px){.df-s-tabs{gap:0}.df-s-tab{font-size:12px;padding:8px}.df-s-page{padding:12px}.df-s-grid{grid-template-columns:repeat(2,1fr);gap:9px}.df-s-card video,.df-s-thumb{height:250px}.df-s-chat{grid-template-columns:1fr}.df-s-users{display:none}.df-s-head{padding:0 10px}.df-s-logo{font-size:17px}}
`;
document.head.appendChild(style);

const root=document.createElement('div');root.id='dfSocial';root.innerHTML=`
<header class="df-s-head"><button class="df-s-icon" id="dfSBack">←</button><div class="df-s-logo">defgodqe <span>social</span></div><nav class="df-s-tabs"><button class="df-s-tab active" data-page="home">Home</button><button class="df-s-tab" data-page="discover">Discover</button><button class="df-s-tab" data-page="messages">Messages</button><button class="df-s-tab" data-page="profile">Profile</button></nav><button class="df-s-icon" id="dfSUpload">＋</button></header><main class="df-s-main" id="dfSMain"></main>
<div class="df-s-modal" id="dfSModal"><div class="df-s-box"><h2>Upload a short</h2><p class="df-s-muted">Choose a video you own or have permission to share.</p><input id="dfSFile" type="file" accept="video/mp4,video/webm,video/quicktime"><input id="dfSTitle" maxlength="100" placeholder="Caption / title"><input id="dfSTags" maxlength="200" placeholder="Tags, e.g. gaming funny minecraft"><div class="df-s-row" style="justify-content:flex-end"><button class="df-s-btn" id="dfSCancel">Cancel</button><button class="df-s-btn primary" id="dfSPost">Post</button></div></div></div>`;
document.body.appendChild(root);
const main=root.querySelector('#dfSMain'),modal=root.querySelector('#dfSModal');
let page='home',chatUser='alex';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function avatar(name){return `<div class="df-s-avatar">${esc((name||'u')[0].toUpperCase())}</div>`}
function renderHome(){main.innerHTML=`<div class="df-s-page"><div class="df-s-compose"><div class="df-s-row"><div>${avatar('you')}</div><div style="flex:1"><b>Create on defgodqe</b><div class="df-s-muted">Share a short with the community.</div></div><button class="df-s-btn primary" id="dfSQuickUpload">Upload video</button></div></div><h2>For you</h2><div class="df-s-grid">${state.videos.length?state.videos.map(card).join(''):`<div class="df-s-card" style="grid-column:1/-1;padding:28px;text-align:center"><div style="font-size:38px">✨</div><h3>Your feed is ready</h3><p class="df-s-muted">Upload the first short and it will appear here.</p></div>`}</div></div>`;root.querySelector('#dfSQuickUpload')?.addEventListener('click',openUpload)}
function card(v){return `<article class="df-s-card"><video src="${esc(v.url)}" controls playsinline preload="metadata"></video><div class="df-s-info"><div class="df-s-row">${avatar(v.user||'you')}<div><b>${esc(v.user||'you')}</b><div class="df-s-muted">${esc(v.title||'')}</div></div></div><div class="df-s-row" style="margin-top:10px"><button class="df-s-btn" data-like="${esc(v.id)}">♥ ${state.liked.includes(v.id)?'Liked':'Like'}</button><button class="df-s-btn" data-follow="${esc(v.user||'you')}">${state.following.includes(v.user)?'Following':'Follow'}</button><span class="df-s-muted">${esc(v.tags||'')}</span></div></div></article>`}
function renderDiscover(){main.innerHTML=`<div class="df-s-page"><h1>Discover</h1><p class="df-s-muted">Explore creators, topics and fresh shorts.</p><div class="df-s-grid">${['Gaming','Funny','Memes','Minecraft','Animals','Sports','Music','Tech','Edits','Satisfying'].map(x=>`<button class="df-s-card" style="height:120px;color:#fff;font-size:18px;cursor:pointer">#${x}</button>`).join('')}</div></div>`}
function renderMessages(){const users=['alex','sam','pixel','nightowl','builder'];const msgs=state.messages[chatUser]||[];main.innerHTML=`<div class="df-s-page"><h1>Messages</h1><div class="df-s-chat"><aside class="df-s-users">${users.map(u=>`<div class="df-s-user ${u===chatUser?'sel':''}" data-chat="${u}">${avatar(u)}<b>${u}</b></div>`).join('')}</aside><section class="df-s-convo"><div class="df-s-msgs">${msgs.length?msgs.map(m=>`<div class="df-s-bubble ${m.me?'me':''}">${esc(m.text)}</div>`).join(''):'<p class="df-s-muted">Start a conversation with '+esc(chatUser)+'.</p>'}</div><form class="df-s-send" id="dfSSend"><input id="dfSMessage" placeholder="Message @${esc(chatUser)}…" autocomplete="off"><button class="df-s-btn primary">Send</button></form></section></div></div>`;main.querySelectorAll('[data-chat]').forEach(x=>x.onclick=()=>{chatUser=x.dataset.chat;renderMessages()});main.querySelector('#dfSSend').onsubmit=e=>{e.preventDefault();const input=main.querySelector('#dfSMessage');if(!input.value.trim())return;(state.messages[chatUser]??=[]).push({text:input.value.trim(),me:true,at:Date.now()});save();renderMessages()}}
function renderProfile(){const mine=state.videos.filter(v=>v.user==='you');main.innerHTML=`<div class="df-s-page"><div class="df-s-compose"><div class="df-s-row">${avatar('you')}<div><h2 style="margin:0">@you</h2><div class="df-s-muted">defgodqe creator</div></div><button class="df-s-btn primary" style="margin-left:auto" id="dfPUpload">Create post</button></div><div style="display:flex;gap:25px;margin-top:18px"><b>${mine.length} posts</b><b>${state.following.length} following</b></div></div><h2>Your shorts</h2><div class="df-s-grid">${mine.length?mine.map(card).join(''):'<p class="df-s-muted">You have not posted yet.</p>'}</div></div>`;root.querySelector('#dfPUpload').onclick=openUpload}
function render(){root.querySelectorAll('.df-s-tab').forEach(b=>b.classList.toggle('active',b.dataset.page===page));({home:renderHome,discover:renderDiscover,messages:renderMessages,profile:renderProfile}[page]||renderHome)();main.scrollTop=0}
function openUpload(){modal.classList.add('open');root.querySelector('#dfSFile').value='';root.querySelector('#dfSTitle').value='';root.querySelector('#dfSTags').value=''}
root.querySelector('#dfSCancel').onclick=()=>modal.classList.remove('open');root.querySelector('#dfSUpload').onclick=openUpload;
root.querySelectorAll('.df-s-tab').forEach(b=>b.onclick=()=>{page=b.dataset.page;render()});
root.querySelector('#dfSBack').onclick=()=>close();
root.querySelector('#dfSPost').onclick=()=>{const file=root.querySelector('#dfSFile').files[0];if(!file)return alert('Choose a video first.');if(!file.type.startsWith('video/'))return alert('Please choose a video file.');const url=URL.createObjectURL(file);state.videos.unshift({id:crypto.randomUUID?.()||String(Date.now()),url,user:'you',title:root.querySelector('#dfSTitle').value.trim()||'New short',tags:root.querySelector('#dfSTags').value.trim(),at:Date.now()});save();modal.classList.remove('open');page='home';render()};
root.addEventListener('click',e=>{const like=e.target.closest('[data-like]');if(like){const id=like.dataset.like;state.liked=state.liked.includes(id)?state.liked.filter(x=>x!==id):state.liked.concat(id);save();render()}const follow=e.target.closest('[data-follow]');if(follow){const u=follow.dataset.follow;state.following=state.following.includes(u)?state.following.filter(x=>x!==u):state.following.concat(u);save();render()}});
function open(){root.classList.add('open');page='home';render()}
function close(){root.classList.remove('open');}
window.defgodqeDoomSocialOpen=open;window.defgodqeDoomSocialClose=close;
})();
