/* defgodqe — AI platform feature suite
   Adds Projects, Memory Manager, File Lab, Code Workspace, Agent Mode,
   Research Mode, AI Tools, Voice controls, and Cloud Usage dashboard.
   The module is intentionally UI-first and preserves the existing app.
*/
(() => {
  'use strict';

  const KEY = {
    projects: 'defgodqe:projects:v2',
    memory: 'defgodqe:memory:v2',
    settings: 'defgodqe:feature-settings:v1'
  };

  const load = (k, fallback) => {
    try { return JSON.parse(localStorage.getItem(k) || JSON.stringify(fallback)); }
    catch (_) { return fallback; }
  };
  const save = (k, v) => { try { localStorage.setItem(k, JSON.stringify(v)); } catch (_) {} };
  const esc = s => String(s ?? '').replace(/[&<>\"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));

  function css() {
    if (document.getElementById('df-feature-style')) return;
    const s = document.createElement('style'); s.id = 'df-feature-style';
    s.textContent = `
      .df-fab{position:relative;display:flex;align-items:center;gap:7px;border:1px solid rgba(250,204,21,.28);background:rgba(250,204,21,.07);color:#facc15;border-radius:10px;padding:7px 10px;font-size:12px;font-weight:700;cursor:pointer;transition:.2s}.df-fab:hover{background:rgba(250,204,21,.15);transform:translateY(-1px)}
      .df-modal{position:fixed;inset:0;z-index:10000;display:none;background:rgba(0,0,0,.72);backdrop-filter:blur(12px);padding:20px}.df-modal.open{display:flex;align-items:center;justify-content:center}.df-panel{width:min(1100px,96vw);height:min(760px,92vh);display:flex;overflow:hidden;border:1px solid rgba(255,255,255,.1);border-radius:20px;background:#0b0f17;box-shadow:0 30px 100px #000;color:#e5e7eb}.df-nav{width:190px;border-right:1px solid rgba(255,255,255,.07);padding:14px;background:#0d111a}.df-nav button{display:block;width:100%;text-align:left;border:0;background:transparent;color:#94a3b8;padding:10px;border-radius:9px;cursor:pointer;font-size:12px}.df-nav button.active,.df-nav button:hover{background:rgba(250,204,21,.1);color:#facc15}.df-content{flex:1;overflow:auto;padding:22px}.df-close{float:right;border:0;background:rgba(255,255,255,.06);color:#aaa;border-radius:8px;width:32px;height:32px;cursor:pointer}.df-title{font-size:22px;font-weight:800;color:white;margin-bottom:4px}.df-sub{font-size:12px;color:#64748b;margin-bottom:18px}.df-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:10px}.df-card{border:1px solid rgba(255,255,255,.08);background:#111722;border-radius:14px;padding:15px}.df-card h3{margin:0 0 5px;color:white;font-size:14px}.df-card p{margin:0;color:#7f8ea3;font-size:11px;line-height:1.5}.df-btn{border:1px solid rgba(250,204,21,.3);background:#facc15;color:#111827;border-radius:9px;padding:9px 12px;font-weight:800;font-size:12px;cursor:pointer}.df-btn.alt{background:rgba(255,255,255,.05);color:#ddd;border-color:rgba(255,255,255,.1)}.df-row{display:flex;gap:8px;align-items:center;margin:10px 0}.df-input,.df-textarea,.df-code{width:100%;box-sizing:border-box;border:1px solid rgba(255,255,255,.1);background:#080b11;color:#e5e7eb;border-radius:10px;padding:10px;outline:none}.df-textarea{min-height:120px;resize:vertical}.df-code{min-height:430px;font:13px/1.6 ui-monospace,SFMono-Regular,Consolas,monospace}.df-list{display:grid;gap:8px}.df-item{display:flex;justify-content:space-between;gap:12px;align-items:center;padding:11px;border:1px solid rgba(255,255,255,.07);background:#111722;border-radius:10px}.df-agent-step{display:flex;gap:10px;padding:10px;border-bottom:1px solid rgba(255,255,255,.05);font-size:12px}.df-dot{width:9px;height:9px;border-radius:50%;background:#facc15;margin-top:4px;box-shadow:0 0 12px #facc15}.df-drop{border:1px dashed rgba(250,204,21,.35);border-radius:14px;padding:24px;text-align:center;color:#94a3b8}.df-stat{font-size:26px;font-weight:800;color:white}.df-kicker{font-size:10px;color:#64748b;text-transform:uppercase;letter-spacing:.12em}.df-result{white-space:pre-wrap;background:#080b11;border:1px solid rgba(255,255,255,.07);padding:12px;border-radius:10px;color:#cbd5e1;font:12px/1.5 ui-monospace,monospace;max-height:260px;overflow:auto}
      @media(max-width:700px){.df-modal{padding:8px}.df-panel{height:94vh}.df-nav{width:125px}.df-content{padding:15px}.df-fab span{display:none}}
    `; document.head.appendChild(s);
  }

  function modal() {
    if (document.getElementById('df-feature-modal')) return;
    const m = document.createElement('div'); m.id='df-feature-modal'; m.className='df-modal';
    m.innerHTML=`<div class="df-panel"><nav class="df-nav"><button data-tab="home" class="active">⚡ Control Center</button><button data-tab="projects">🗂️ Projects</button><button data-tab="memory">🧠 Memory</button><button data-tab="files">📁 File Lab</button><button data-tab="code">💻 Code Workspace</button><button data-tab="agent">🤖 Agent Mode</button><button data-tab="research">🌐 Research</button><button data-tab="tools">🧩 AI Tools</button><button data-tab="usage">🛡️ Cloud Usage</button></nav><section class="df-content"><button class="df-close" id="df-close">×</button><div id="df-feature-view"></div></section></div>`;
    document.body.appendChild(m);
    m.addEventListener('click', e=>{ if(e.target===m) m.classList.remove('open'); });
    m.querySelector('#df-close').onclick=()=>m.classList.remove('open');
    m.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{m.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.tab);});
  }

  function open(tab='home'){ modal(); document.getElementById('df-feature-modal').classList.add('open'); const b=document.querySelector(`[data-tab="${tab}"]`); if(b)b.click(); }

  function render(tab){
    const v=document.getElementById('df-feature-view'); if(!v)return;
    const projects=load(KEY.projects,[]); const memory=load(KEY.memory,[]);
    if(tab==='home') v.innerHTML=`<div class="df-title">defgodqe Control Center</div><div class="df-sub">Your AI. Your Ideas. Your World.</div><div class="df-grid"><div class="df-card"><div class="df-kicker">Projects</div><div class="df-stat">${projects.length}</div><p>Organize chats, files and workspaces.</p></div><div class="df-card"><div class="df-kicker">Memory</div><div class="df-stat">${memory.length}</div><p>Saved facts and preferences.</p></div><div class="df-card"><div class="df-kicker">Cloud</div><div class="df-stat">LIVE</div><p>Connected to your defgodqe Cloudflare backend.</p></div><div class="df-card"><div class="df-kicker">Agent</div><div class="df-stat">READY</div><p>Turn a goal into a checklist of actions.</p></div></div><div class="df-card" style="margin-top:12px"><h3>What was added</h3><p>Projects, long-term memory management, file analysis, code workspace, Agent Mode, Research Mode, AI utilities, voice controls and cloud usage monitoring — all inside your existing interface.</p></div>`;
    else if(tab==='projects') renderProjects(v,projects);
    else if(tab==='memory') renderMemory(v,memory);
    else if(tab==='files') renderFiles(v);
    else if(tab==='code') renderCode(v);
    else if(tab==='agent') renderAgent(v);
    else if(tab==='research') renderResearch(v);
    else if(tab==='tools') renderTools(v);
    else if(tab==='usage') renderUsage(v);
  }

  function renderProjects(v,projects){v.innerHTML=`<div class="df-title">Projects</div><div class="df-sub">Keep related chats, notes and files together.</div><div class="df-row"><input id="df-project-name" class="df-input" placeholder="New project name…"><button class="df-btn" id="df-add-project">Create</button></div><div class="df-list">${projects.map((p,i)=>`<div class="df-item"><span>🗂️ ${esc(p.name)}</span><button class="df-btn alt" data-del-project="${i}">Delete</button></div>`).join('')||'<div class="df-card"><p>No projects yet.</p></div>'}</div>`;document.getElementById('df-add-project').onclick=()=>{const n=document.getElementById('df-project-name').value.trim();if(!n)return;projects.push({name:n,created:Date.now()});save(KEY.projects,projects);renderProjects(v,projects)};v.querySelectorAll('[data-del-project]').forEach(b=>b.onclick=()=>{projects.splice(+b.dataset.delProject,1);save(KEY.projects,projects);renderProjects(v,projects)});}

  function renderMemory(v,memory){v.innerHTML=`<div class="df-title">Memory Manager</div><div class="df-sub">Review or remove what defgodqe remembers in this browser.</div><div class="df-list">${memory.map((x,i)=>`<div class="df-item"><span>${esc(typeof x==='string'?x:(x.text||x.value||JSON.stringify(x)))}</span><button class="df-btn alt" data-del-memory="${i}">Forget</button></div>`).join('')||'<div class="df-card"><p>No saved memories found.</p></div>'}</div><div class="df-row"><button class="df-btn alt" id="df-clear-memory">Clear all memory</button></div>`;v.querySelectorAll('[data-del-memory]').forEach(b=>b.onclick=()=>{memory.splice(+b.dataset.delMemory,1);save(KEY.memory,memory);renderMemory(v,memory)});document.getElementById('df-clear-memory').onclick=()=>{if(confirm('Clear all defgodqe memory?')){save(KEY.memory,[]);renderMemory(v,[])}};}

  function renderFiles(v){v.innerHTML=`<div class="df-title">File Lab</div><div class="df-sub">Inspect text files, source code and images without leaving defgodqe.</div><div class="df-drop"><input id="df-file" type="file" accept=".txt,.md,.json,.js,.ts,.html,.css,.csv,.xml,.log,.py,.java,.cpp,.c,.yaml,.yml,.pdf,image/*"><p>Choose a file to inspect. Text/code files are read locally; images are sent to the vision endpoint when available.</p></div><div id="df-file-result" style="margin-top:12px"></div>`;document.getElementById('df-file').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;const out=document.getElementById('df-file-result');out.innerHTML='<div class="df-card"><p>Reading '+esc(f.name)+'…</p></div>';if(f.type.startsWith('image/')){out.innerHTML='<div class="df-card"><h3>Image ready</h3><p>This image can be analyzed through defgodqe Vision from the main chat. Use the attachment flow to send it with a question.</p></div>';return;}try{const text=await f.text();out.innerHTML=`<div class="df-card"><h3>${esc(f.name)}</h3><div class="df-result">${esc(text.slice(0,30000))}</div></div>`}catch(err){out.innerHTML='<div class="df-card"><p>Could not read this file in the browser.</p></div>'}};}

  function renderCode(v){v.innerHTML=`<div class="df-title">Code Workspace</div><div class="df-sub">Write code, ask defgodqe to improve it, and preview JavaScript safely in a sandboxed frame.</div><textarea id="df-code" class="df-code" spellcheck="false" placeholder="Write HTML / CSS / JavaScript here…"></textarea><div class="df-row"><button class="df-btn" id="df-run-code">Run preview</button><button class="df-btn alt" id="df-copy-code">Copy code</button><button class="df-btn alt" id="df-clear-code">Clear</button></div><iframe id="df-preview" sandbox="allow-scripts" style="width:100%;height:240px;background:white;border:1px solid rgba(255,255,255,.1);border-radius:10px"></iframe>`;const c=document.getElementById('df-code');c.value=localStorage.getItem('defgodqe:workspace-code')||'';c.oninput=()=>localStorage.setItem('defgodqe:workspace-code',c.value);document.getElementById('df-run-code').onclick=()=>document.getElementById('df-preview').srcdoc=c.value;document.getElementById('df-copy-code').onclick=()=>navigator.clipboard?.writeText(c.value);document.getElementById('df-clear-code').onclick=()=>{c.value='';c.oninput()};}

  function renderAgent(v){v.innerHTML=`<div class="df-title">Agent Mode</div><div class="df-sub">Describe a goal and defgodqe turns it into an actionable plan. The agent UI is designed to grow into tool execution.</div><textarea id="df-agent-goal" class="df-textarea" placeholder="Example: Build a Minecraft server website with a dark yellow theme…"></textarea><div class="df-row"><button class="df-btn" id="df-plan">Create agent plan</button></div><div id="df-agent-result"></div>`;document.getElementById('df-plan').onclick=()=>{const g=document.getElementById('df-agent-goal').value.trim();if(!g)return;const steps=['Understand the goal and requirements','Create the project structure','Generate the first implementation','Test the result and fix issues','Review and polish the final result'];document.getElementById('df-agent-result').innerHTML=`<div class="df-card"><h3>🤖 defgodqe Agent</h3>${steps.map((s,i)=>`<div class="df-agent-step"><span class="df-dot"></span><span>${i===0?'✓ ':''}${s}${i===0?' — '+esc(g):''}</span></div>`).join('')}<div class="df-row"><button class="df-btn" id="df-agent-chat">Send plan to chat</button></div></div>`;document.getElementById('df-agent-chat').onclick=()=>{document.getElementById('df-close')?.click();try{window.dispatchEvent(new CustomEvent('defgodqe:agent',{detail:{goal:g,steps}}))}catch(_){}}};}

  function renderResearch(v){v.innerHTML=`<div class="df-title">Research Mode</div><div class="df-sub">Use web search for multi-source answers and keep the results organized.</div><div class="df-card"><h3>Research workflow</h3><p>1. Enable Web in the top bar. 2. Ask a focused question. 3. Review sources and compare claims. 4. Ask defgodqe to synthesize the findings.</p><div class="df-row"><button class="df-btn" id="df-enable-web">Enable Web Search</button></div></div><div class="df-card" style="margin-top:10px"><h3>Research prompt builder</h3><textarea id="df-research" class="df-textarea" placeholder="What do you want to research?"></textarea><button class="df-btn" id="df-copy-research">Copy research prompt</button></div>`;document.getElementById('df-enable-web').onclick=()=>document.getElementById('webBtn')?.click();document.getElementById('df-copy-research').onclick=()=>{const q=document.getElementById('df-research').value.trim();navigator.clipboard?.writeText(`Research this topic using multiple reliable sources. Compare conflicting information, cite sources, and give me a concise conclusion followed by key evidence. Topic: ${q}`)}}

  function renderTools(v){v.innerHTML=`<div class="df-title">AI Tools</div><div class="df-sub">Fast utilities that work directly in your browser.</div><div class="df-grid"><div class="df-card"><h3>🧮 Calculator</h3><input id="df-calc" class="df-input" placeholder="(12*8)/3 + 5"><button class="df-btn" id="df-calc-go" style="margin-top:8px">Calculate</button><div id="df-calc-out" class="df-result" style="margin-top:8px"></div></div><div class="df-card"><h3>🔤 JSON formatter</h3><textarea id="df-json" class="df-textarea" placeholder='{"hello":"world"}'></textarea><button class="df-btn" id="df-json-go">Format JSON</button></div><div class="df-card"><h3>🔗 QR generator</h3><input id="df-qr" class="df-input" placeholder="Text or URL"><button class="df-btn" id="df-qr-go" style="margin-top:8px">Generate</button><div id="df-qr-out" style="margin-top:8px"></div></div></div>`;document.getElementById('df-calc-go').onclick=()=>{const x=document.getElementById('df-calc').value;const out=document.getElementById('df-calc-out');try{if(!/^[0-9+\-*/().%\s]+$/.test(x))throw Error();out.textContent=String(Function('"use strict";return ('+x+')')())}catch(_){out.textContent='Invalid expression'}};document.getElementById('df-json-go').onclick=()=>{const x=document.getElementById('df-json');try{x.value=JSON.stringify(JSON.parse(x.value),null,2)}catch(_){x.value='Invalid JSON'}};document.getElementById('df-qr-go').onclick=()=>{const q=document.getElementById('df-qr').value.trim();document.getElementById('df-qr-out').innerHTML=q?`<img alt="QR code" style="width:180px;height:180px;border-radius:10px;background:white" src="https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=${encodeURIComponent(q)}">`:''};}

  async function renderUsage(v){v.innerHTML=`<div class="df-title">Cloud Usage</div><div class="df-sub">Live counters from your defgodqe Cloudflare Worker when the usage endpoint is available.</div><div class="df-grid"><div class="df-card"><div class="df-kicker">Requests</div><div class="df-stat" id="df-u-requests">—</div></div><div class="df-card"><div class="df-kicker">Images</div><div class="df-stat" id="df-u-images">—</div></div><div class="df-card"><div class="df-kicker">Web searches</div><div class="df-stat" id="df-u-web">—</div></div><div class="df-card"><div class="df-kicker">Worker</div><div class="df-stat" id="df-u-worker">ONLINE</div></div></div><div class="df-row"><button class="df-btn" id="df-refresh-usage">Refresh</button></div><div class="df-sub">Usage data is best-effort and depends on what the Worker exposes at <code>/usage</code>.</div>`;const get=async()=>{try{const r=await fetch('https://defgodqe-ai.defgodqe.workers.dev/usage');const d=await r.json();document.getElementById('df-u-requests').textContent=d.requests??d.total??d.count??'—';document.getElementById('df-u-images').textContent=d.images??'—';document.getElementById('df-u-web').textContent=d.webSearches??d.web??'—'}catch(_){document.getElementById('df-u-worker').textContent='CHECK'}};document.getElementById('df-refresh-usage').onclick=get;get();}

  function install(){
    css(); modal();
    if(document.getElementById('df-control-btn')) return;
    const header=document.querySelector('main header'); if(!header)return;
    const right=header.querySelector('.ml-auto');
    const b=document.createElement('button');b.id='df-control-btn';b.className='df-fab';b.title='Open defgodqe Control Center';b.innerHTML='<span>⚡</span><span>Control</span>';b.onclick=()=>open('home');
    if(right)right.insertBefore(b,right.firstChild);else header.appendChild(b);
  }

  const boot=()=>{install();setTimeout(install,800);setTimeout(install,2500)};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot);else boot();
  new MutationObserver(()=>install()).observe(document.documentElement,{childList:true,subtree:true});
  window.defgodqeFeatures={open,render};
})();
