/* defgodqe — mini arcade: 4 futuristic games */
(function(){
  'use strict';
  if(window.__defgodqeMiniArcade) return;
  window.__defgodqeMiniArcade=true;

  const css=`
#dfGameBtn{position:relative;overflow:hidden}#dfGameBtn::after{content:"";position:absolute;inset:0;background:linear-gradient(90deg,transparent,rgba(250,204,21,.22),transparent);transform:translateX(-100%);animation:dfArcadeShine 2.5s infinite}@keyframes dfArcadeShine{60%,100%{transform:translateX(100%)}}
#dfGameOverlay{position:fixed;inset:0;z-index:10001;display:none;align-items:center;justify-content:center;padding:16px;background:rgba(2,5,10,.72);backdrop-filter:blur(18px)}#dfGamePanel{position:relative;width:min(900px,96vw);height:min(680px,92vh);overflow:hidden;border:1px solid rgba(250,204,21,.32);border-radius:26px;background:linear-gradient(145deg,#121a29,#05070c);box-shadow:0 0 100px rgba(250,204,21,.18),0 30px 100px rgba(0,0,0,.65);font-family:Inter,system-ui,sans-serif}#dfGameCanvas{display:block;width:100%;height:100%;touch-action:none}#dfGameClose{position:absolute;right:14px;top:12px;z-index:8;width:40px;height:40px;border:1px solid rgba(255,255,255,.14);border-radius:12px;background:rgba(8,12,20,.8);color:#fff;font-size:24px;cursor:pointer}#dfGameHud{position:absolute;left:18px;right:70px;top:14px;z-index:4;display:flex;justify-content:space-between;color:#cbd5e1;font:700 13px Inter;pointer-events:none}#dfGameHud b{color:#fde047;font-size:20px;text-shadow:0 0 15px #facc15}.dfArcadeScreen{position:absolute;inset:0;z-index:6;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;background:radial-gradient(circle at 50% 42%,rgba(250,204,21,.13),rgba(4,7,12,.95) 62%);padding:24px}.dfArcadeScreen h2{margin:0 0 8px;font-size:36px;color:#fff}.dfArcadeScreen h2 span{color:#facc15;text-shadow:0 0 24px rgba(250,204,21,.55)}.dfArcadeScreen p{color:#94a3b8;margin:0 0 22px}.dfGameChoices{display:grid;grid-template-columns:repeat(2,minmax(180px,280px));gap:12px;width:min(620px,100%)}.dfGameChoice{padding:18px;border:1px solid rgba(250,204,21,.18);border-radius:18px;background:linear-gradient(145deg,rgba(255,255,255,.07),rgba(255,255,255,.025));color:#fff;text-align:left;cursor:pointer;transition:.2s;box-shadow:0 8px 30px rgba(0,0,0,.2)}.dfGameChoice:hover{transform:translateY(-3px);border-color:rgba(250,204,21,.55);box-shadow:0 0 28px rgba(250,204,21,.15)}.dfGameChoice strong{display:block;color:#fde047;font-size:17px;margin-bottom:5px}.dfGameChoice small{color:#94a3b8}.dfArcadeBack{margin-top:18px;background:transparent;border:1px solid rgba(255,255,255,.12);color:#cbd5e1;border-radius:12px;padding:9px 16px;cursor:pointer}.dfGameTouch{position:absolute;bottom:18px;left:18px;right:18px;display:none;justify-content:space-between;z-index:5;pointer-events:none}.dfGameTouch button{pointer-events:auto;width:62px;height:52px;border:1px solid rgba(250,204,21,.25);border-radius:15px;background:rgba(10,14,22,.72);color:#fde047;font-size:22px}.dfMemoryGrid{display:grid;grid-template-columns:repeat(4,70px);gap:10px;margin:20px auto}.dfMemoryCard{width:70px;height:70px;border:1px solid rgba(250,204,21,.22);border-radius:14px;background:#101827;color:transparent;font-size:24px;cursor:pointer}.dfMemoryCard.revealed,.dfMemoryCard.matched{color:#fde047;background:rgba(250,204,21,.12);box-shadow:0 0 20px rgba(250,204,21,.18)}
@media(max-width:600px){#dfGamePanel{width:100vw;height:100dvh;border-radius:0}.dfArcadeScreen h2{font-size:28px}.dfGameChoices{grid-template-columns:1fr}.dfGameTouch{display:flex}.dfMemoryGrid{grid-template-columns:repeat(4,58px);gap:7px}.dfMemoryCard{width:58px;height:58px}}
`;
  const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);

  function addButton(){
    if(document.getElementById('dfGameBtn')) return;
    const sidebar=document.getElementById('sidebar');if(!sidebar)return;
    const user=sidebar.querySelector('#authRow')?.parentElement;if(!user)return;
    const wrap=document.createElement('div');wrap.className='px-3 pb-2';
    wrap.innerHTML='<button id="dfGameBtn" type="button" class="flex w-full items-center gap-2 rounded-xl border border-brand/20 bg-brand/5 px-3 py-2.5 text-sm font-semibold text-slate-200 transition hover:bg-brand/10"><span style="font-size:17px">◈</span><span>Mini arcade</span><span style="margin-left:auto;font-size:10px;color:#facc15">4 GAMES</span></button>';
    user.before(wrap);document.getElementById('dfGameBtn').onclick=openArcade;
  }

  const overlay=document.createElement('div');overlay.id='dfGameOverlay';overlay.innerHTML=`<div id="dfGamePanel"><canvas id="dfGameCanvas"></canvas><div id="dfGameHud"><span id="dfHudLeft">SCORE <b>0</b></span><span id="dfHudRight">BEST <b>0</b></span></div><button id="dfGameClose" aria-label="Close games">×</button><div id="dfArcadeMenu" class="dfArcadeScreen"><h2>DEF<span>ARCADE</span></h2><p>Four fast futuristic games. Beat your best score.</p><div class="dfGameChoices"><button class="dfGameChoice" data-game="run"><strong>⚡ Neon Orb Run</strong><small>Dodge falling energy blocks.</small></button><button class="dfGameChoice" data-game="breaker"><strong>◈ Cyber Breaker</strong><small>Smash the neon core with your paddle.</small></button><button class="dfGameChoice" data-game="memory"><strong>▣ Memory Matrix</strong><small>Match the glowing symbols as fast as possible.</small></button><button class="dfGameChoice" data-game="meteor"><strong>✦ Meteor Blaster</strong><small>Blast incoming meteors and survive.</small></button></div></div><div class="dfGameTouch"><button id="dfTouchLeft">‹</button><button id="dfTouchRight">›</button></div></div>`;
  document.body.appendChild(overlay);
  const canvas=overlay.querySelector('#dfGameCanvas'),ctx=canvas.getContext('2d'),menu=overlay.querySelector('#dfArcadeMenu');
  let raf=0,running=false,game='',score=0,best=0,last=0,keys={},pointer={active:false,x:0};let state={};
  const bestKey=g=>'df_game_best_'+g;
  function resize(){const r=canvas.getBoundingClientRect(),d=devicePixelRatio||1;canvas.width=Math.max(1,r.width*d);canvas.height=Math.max(1,r.height*d);ctx.setTransform(d,0,0,d,0,0);}
  function openArcade(){overlay.style.display='flex';resize();menu.style.display='flex';hud(false)}
  function closeArcade(){running=false;cancelAnimationFrame(raf);overlay.style.display='none';}
  function hud(show=true){overlay.querySelector('#dfGameHud').style.display=show?'flex':'none'}
  function setHud(l,r){overlay.querySelector('#dfHudLeft').innerHTML=l;overlay.querySelector('#dfHudRight').innerHTML=r}
  function start(g){game=g;score=0;best=Number(localStorage.getItem(bestKey(g))||0);running=true;last=performance.now();menu.style.display='none';hud(true);resize();if(g==='run')initRun();if(g==='breaker')initBreaker();if(g==='memory'){hud(false);initMemory();return}if(g==='meteor')initMeteor();raf=requestAnimationFrame(loop)}
  function end(title,msg){running=false;cancelAnimationFrame(raf);if(score>best){best=Math.floor(score);localStorage.setItem(bestKey(game),best)}menu.style.display='flex';menu.innerHTML=`<h2>${title}</h2><p>${msg} • Best: ${best}</p><div class="dfGameChoices"><button class="dfGameChoice" id="dfReplay"><strong>↻ Play again</strong><small>Try to beat your best.</small></button><button class="dfGameChoice" id="dfBack"><strong>⌂ Game select</strong><small>Choose another arcade game.</small></button></div>`;hud(false);overlay.querySelector('#dfReplay').onclick=()=>start(game);overlay.querySelector('#dfBack').onclick=()=>showMenu()}
  function showMenu(){running=false;cancelAnimationFrame(raf);menu.innerHTML='<h2>DEF<span>ARCADE</span></h2><p>Four fast futuristic games. Beat your best score.</p><div class="dfGameChoices"><button class="dfGameChoice" data-game="run"><strong>⚡ Neon Orb Run</strong><small>Dodge falling energy blocks.</small></button><button class="dfGameChoice" data-game="breaker"><strong>◈ Cyber Breaker</strong><small>Smash the neon core with your paddle.</small></button><button class="dfGameChoice" data-game="memory"><strong>▣ Memory Matrix</strong><small>Match the glowing symbols as fast as possible.</small></button><button class="dfGameChoice" data-game="meteor"><strong>✦ Meteor Blaster</strong><small>Blast incoming meteors and survive.</small></button></div>';menu.style.display='flex';menu.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>start(b.dataset.game));hud(false)}
  menu.querySelectorAll('[data-game]').forEach(b=>b.onclick=()=>start(b.dataset.game));overlay.querySelector('#dfGameClose').onclick=closeArcade;

  function glowCircle(x,y,r,fill='#fde047'){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.shadowBlur=28;ctx.shadowColor='#facc15';ctx.fillStyle=fill;ctx.fill();ctx.shadowBlur=0}
  function bg(w,h){ctx.fillStyle='#05080e';ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(250,204,21,.045)';for(let x=0;x<w;x+=36){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=36){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}}

  // 1. Neon Orb Run
  function initRun(){const r=canvas.getBoundingClientRect();state={p:{x:r.width/2,y:r.height-70,r:15},blocks:[],spawn:.3}}
  function loopRun(dt){const r=canvas.getBoundingClientRect();bg(r.width,r.height);let dx=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0);state.p.x=Math.max(15,Math.min(r.width-15,state.p.x+dx*340*dt));if(pointer.active)state.p.x=Math.max(15,Math.min(r.width-15,pointer.x));state.spawn-=dt;if(state.spawn<=0){let s=24+Math.random()*40;state.blocks.push({x:Math.random()*(r.width-s),y:-s,w:s,h:s,v:190+Math.random()*100+score});state.spawn=Math.max(.25,.68-score/200)}state.blocks.forEach(b=>{b.y+=b.v*dt;ctx.shadowBlur=20;ctx.shadowColor='#facc15';ctx.fillStyle='#facc15';ctx.fillRect(b.x,b.y,b.w,b.h);ctx.shadowBlur=0});state.blocks=state.blocks.filter(b=>b.y<r.height+50);score+=dt*10;glowCircle(state.p.x,state.p.y,15);for(const b of state.blocks){const cx=Math.max(b.x,Math.min(state.p.x,b.x+b.w)),cy=Math.max(b.y,Math.min(state.p.y,b.y+b.h));if((state.p.x-cx)**2+(state.p.y-cy)**2<19**2)return end('GAME OVER','Score: '+Math.floor(score))}setHud('SCORE <b>'+Math.floor(score)+'</b>','BEST <b>'+best+'</b>')}

  // 2. Cyber Breaker
  function initBreaker(){const r=canvas.getBoundingClientRect();let bricks=[];for(let row=0;row<5;row++)for(let col=0;col<9;col++)bricks.push({x:28+col*((r.width-56)/9),y:65+row*29,w:(r.width-64)/9,h:20,on:true});state={p:r.width/2,ball:{x:r.width/2,y:r.height-100,vx:210,vy:-250,r:8},bricks,miss:0}}
  function loopBreaker(dt){const r=canvas.getBoundingClientRect();bg(r.width,r.height);state.p=Math.max(45,Math.min(r.width-45,state.p+((keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0))*430*dt));if(pointer.active)state.p=pointer.x;let b=state.ball;b.x+=b.vx*dt;b.y+=b.vy*dt;if(b.x<b.r||b.x>r.width-b.r)b.vx*=-1;if(b.y<b.r+45)b.vy=Math.abs(b.vy);if(b.y>r.height-55&&b.x>state.p-52&&b.x<state.p+52){b.vy=-Math.abs(b.vy);b.vx+=(b.x-state.p)*3}for(const q of state.bricks)if(q.on&&b.x>q.x&&b.x<q.x+q.w&&b.y>b.y-q.h&&b.y<q.y+q.h){if(b.y>=q.y-4&&b.vy>0||b.y<=q.y+q.h+4&&b.vy<0)b.vy*=-1;q.on=false;score+=10}state.bricks.forEach(q=>{if(q.on){ctx.fillStyle='#facc15';ctx.shadowBlur=12;ctx.shadowColor='#facc15';ctx.fillRect(q.x,q.y,q.w,q.h);ctx.shadowBlur=0}});ctx.fillStyle='#fde047';ctx.fillRect(state.p-52,r.height-38,104,10);glowCircle(b.x,b.y,8);if(b.y>r.height+20)return end('CORE LOST','Score: '+Math.floor(score));if(state.bricks.every(q=>!q.on)){score+=100;initBreaker()}setHud('SCORE <b>'+Math.floor(score)+'</b>','BEST <b>'+best+'</b>')}

  // 3. Memory Matrix — DOM cards for a different gameplay style
  function initMemory(){const symbols=['◆','●','▲','✦','⬢','✚','◇','★'];let vals=[...symbols,...symbols].sort(()=>Math.random()-.5);let found=0,open=[],moves=0,start=performance.now();menu.innerHTML='<h2>MEMORY <span>MATRIX</span></h2><p>Find every matching pair.</p><div class="dfMemoryGrid"></div><p id="dfMemInfo">Moves: 0</p><button class="dfArcadeBack" id="dfMemBack">Back to arcade</button>';const grid=menu.querySelector('.dfMemoryGrid');vals.forEach((v,i)=>{const c=document.createElement('button');c.className='dfMemoryCard';c.textContent=v;c.onclick=()=>{if(c.classList.contains('revealed')||c.classList.contains('matched')||open.length===2)return;c.classList.add('revealed');open.push({c,v});moves++;menu.querySelector('#dfMemInfo').textContent='Moves: '+moves;if(open.length===2){const [a,b]=open;if(a.v===b.v){a.c.classList.add('matched');b.c.classList.add('matched');open=[];found+=2;if(found===vals.length){score=Math.max(100,1000-Math.floor((performance.now()-start)/100)-moves*15);end('MATRIX CLEARED','Score: '+Math.floor(score))}}else setTimeout(()=>{a.c.classList.remove('revealed');b.c.classList.remove('revealed');open=[]},500)}};grid.appendChild(c)});menu.querySelector('#dfMemBack').onclick=showMenu}

  // 4. Meteor Blaster
  function initMeteor(){const r=canvas.getBoundingClientRect();state={ship:{x:r.width/2,y:r.height-65},shots:[],meteors:[],spawn:.4,cool:0,lives:3}}
  function loopMeteor(dt){const r=canvas.getBoundingClientRect();bg(r.width,r.height);let dx=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0);state.ship.x=Math.max(22,Math.min(r.width-22,state.ship.x+dx*360*dt));if(pointer.active)state.ship.x=pointer.x;if((keys[' ']||keys.ArrowUp)&&state.cool<=0){state.shots.push({x:state.ship.x,y:state.ship.y-18,v:560});state.cool=.18}state.cool-=dt;state.spawn-=dt;if(state.spawn<=0){let rr=12+Math.random()*20;state.meteors.push({x:rr+Math.random()*(r.width-2*rr),y:-rr,r:rr,v:100+Math.random()*130+score*.2});state.spawn=Math.max(.18,.6-score/250)}state.shots.forEach(s=>s.y-=s.v*dt);state.meteors.forEach(m=>m.y+=m.v*dt);for(const s of state.shots)for(const m of state.meteors)if((s.x-m.x)**2+(s.y-m.y)**2<(m.r+5)**2){m.dead=true;s.dead=true;score+=10}state.shots=state.shots.filter(s=>!s.dead&&s.y>-20);state.meteors=state.meteors.filter(m=>!m.dead&&m.y<r.height+40);for(const m of state.meteors){ctx.beginPath();ctx.arc(m.x,m.y,m.r,0,Math.PI*2);ctx.fillStyle='#facc15';ctx.shadowBlur=20;ctx.shadowColor='#facc15';ctx.fill();ctx.shadowBlur=0}for(const s of state.shots){ctx.fillStyle='#fff';ctx.fillRect(s.x-2,s.y-9,4,18)}ctx.fillStyle='#fde047';ctx.beginPath();ctx.moveTo(state.ship.x,state.ship.y-20);ctx.lineTo(state.ship.x-20,state.ship.y+18);ctx.lineTo(state.ship.x+20,state.ship.y+18);ctx.closePath();ctx.fill();for(const m of state.meteors)if((m.x-state.ship.x)**2+(m.y-state.ship.y)**2<(m.r+17)**2){m.dead=true;state.lives--}state.meteors=state.meteors.filter(m=>!m.dead);if(state.lives<=0)return end('SHIP DESTROYED','Score: '+Math.floor(score));setHud('SCORE <b>'+Math.floor(score)+'</b>','LIVES <b>'+state.lives+'</b>')}

  function loop(t){if(!running)return;const dt=Math.min(.035,(t-last)/1000);last=t;try{if(game==='run')loopRun(dt);else if(game==='breaker')loopBreaker(dt);else if(game==='meteor')loopMeteor(dt)}catch(e){console.error('def arcade',e);running=false}if(running)raf=requestAnimationFrame(loop)}
  canvas.addEventListener('pointerdown',e=>{pointer.active=true;pointer.x=e.clientX-canvas.getBoundingClientRect().left});canvas.addEventListener('pointermove',e=>{if(pointer.active)pointer.x=e.clientX-canvas.getBoundingClientRect().left});window.addEventListener('pointerup',()=>pointer.active=false);window.addEventListener('keydown',e=>{keys[e.key]=true;if(e.key==='Escape')closeArcade()});window.addEventListener('keyup',e=>keys[e.key]=false);overlay.querySelector('#dfTouchLeft').onpointerdown=()=>keys.ArrowLeft=true;overlay.querySelector('#dfTouchRight').onpointerdown=()=>keys.ArrowRight=true;window.addEventListener('pointerup',()=>{keys.ArrowLeft=false;keys.ArrowRight=false});window.addEventListener('resize',()=>{if(overlay.style.display==='flex')resize()});
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',addButton,{once:true});else addButton();const observer=new MutationObserver(addButton);observer.observe(document.body,{childList:true,subtree:true});
})();
