/* defgodqe — NEON TAG: massive glowing laser freeze arena */
(() => {
  'use strict';
  if (window.__defgodqeMultiplayerGame) return;
  window.__defgodqeMultiplayerGame = true;

  const DEFAULT_SERVER = 'wss://defgodqe-ai.defgodqe.workers.dev/game';
  const root = document.createElement('div');
  root.id = 'dfMP';
  root.innerHTML = `
    <style>
      #dfMP{position:fixed;inset:0;z-index:100100;background:rgba(1,3,8,.96);backdrop-filter:blur(18px);display:none;align-items:center;justify-content:center;padding:10px;color:#fff;font-family:Inter,system-ui,sans-serif}
      #dfMP.open{display:flex}#dfMPPanel{position:relative;width:min(1500px,99vw);height:min(900px,97vh);overflow:hidden;border:1px solid rgba(250,204,21,.45);border-radius:28px;background:#02050a;box-shadow:0 0 120px rgba(250,204,21,.14),0 30px 120px #000}
      #dfMPCanvas{position:absolute;inset:0;width:100%;height:100%;touch-action:none}
      #dfMPTop{position:absolute;left:24px;right:65px;top:18px;z-index:5;display:flex;align-items:center;gap:14px;pointer-events:none;flex-wrap:wrap}.dfMPTitle{font-size:18px;font-weight:950;letter-spacing:.12em;text-shadow:0 0 25px #facc15}.dfMPTitle span{color:#facc15}.dfMPBadge{padding:7px 10px;border:1px solid #facc1540;border-radius:999px;background:#facc150b;color:#fde047;font-weight:900;font-size:11px}.dfMPStats{color:#94a3b8;font-size:11px}.dfMPStats b{color:#fde047;font-size:18px;margin-left:4px}
      #dfMPClose{position:absolute;right:13px;top:13px;z-index:20;width:42px;height:42px;border-radius:13px;border:1px solid #fff2;background:#080c14e8;color:#fff;font-size:24px;cursor:pointer}
      #dfMPLobby{position:absolute;inset:0;z-index:10;display:flex;align-items:center;justify-content:center;background:radial-gradient(circle at 50% 30%,#facc1520,#03060bf5 60%);padding:24px;box-sizing:border-box}.dfMPCard{width:min(680px,100%);max-height:92%;overflow:auto;padding:34px;border:1px solid #facc1538;border-radius:28px;background:linear-gradient(145deg,#0c111bef,#05080eee);box-shadow:0 25px 90px #000a}.dfMPCard h1{margin:0;font-size:58px;letter-spacing:-.06em}.dfMPCard h1 span{color:#facc15;text-shadow:0 0 35px #facc15}.dfMPCard p{color:#94a3b8;line-height:1.6}.dfMPFeatures{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:18px 0}.dfMPFeature{padding:12px;border:1px solid #fff1;border-radius:14px;background:#ffffff05}.dfMPFeature b{display:block;color:#fde047;font-size:12px}.dfMPFeature small{color:#64748b}.dfMPInput{width:100%;box-sizing:border-box;padding:14px;margin:6px 0;border-radius:13px;border:1px solid #fff2;background:#03060b;color:#fff;outline:0;font-size:16px}.dfMPInput:focus{border-color:#facc1580;box-shadow:0 0 0 3px #facc1512}.dfMPBtns{display:flex;gap:9px;flex-wrap:wrap;margin-top:12px}.dfMPBtn{border:1px solid #fff2;background:#ffffff0b;color:#fff;border-radius:13px;padding:12px 17px;font-weight:850;cursor:pointer}.dfMPBtn.primary{background:#facc15;color:#111827;border-color:#facc15;box-shadow:0 0 28px #facc1530}.dfMPStatus{min-height:20px;color:#94a3b8;font-size:13px;margin-top:11px}.dfMPRoom{font-size:38px;letter-spacing:.2em;font-weight:950;color:#fde047;text-align:center;margin:14px 0;text-shadow:0 0 25px #facc15}.dfMPHint{font-size:11px;color:#64748b;text-align:center}
      #dfMPHud{position:absolute;left:20px;right:20px;bottom:17px;z-index:5;display:none;align-items:flex-end;justify-content:space-between;gap:10px;pointer-events:none}.dfMPInfo{padding:10px 13px;border:1px solid #fff1;border-radius:14px;background:#05080dcc;backdrop-filter:blur(12px);color:#cbd5e1;font-size:12px;font-weight:800;max-width:70%}.dfMPTouch{display:none;grid-template-columns:repeat(3,54px);gap:6px;pointer-events:auto}.dfMPTouch button{width:54px;height:50px;border-radius:14px;border:1px solid #facc1545;background:#080c14dd;color:#fde047;font-size:20px;touch-action:none}.dfMPTouch .empty{visibility:hidden}
      @media(max-width:700px){#dfMP{padding:0}#dfMPPanel{width:100vw;height:100dvh;border-radius:0}.dfMPCard{padding:22px}.dfMPCard h1{font-size:40px}.dfMPFeatures{grid-template-columns:1fr 1fr}.dfMPTouch{display:grid}}
    </style>
    <div id="dfMPPanel">
      <canvas id="dfMPCanvas"></canvas>
      <div id="dfMPTop"><div class="dfMPTitle">NEON <span>TAG</span></div><div class="dfMPBadge">FREEZE ARENA</div><div class="dfMPStats">PLAYERS <b id="dfMPPlayers">0</b></div><div class="dfMPStats">FROZEN <b id="dfMPFrozen">0</b></div><div class="dfMPStats">TIME <b id="dfMPTime">3:00</b></div></div>
      <button id="dfMPClose" aria-label="Close game">×</button>
      <div id="dfMPLobby"><div class="dfMPCard"><h1>NEON <span>TAG</span></h1><p>Enter the massive glowing arena. Sprint, dodge and fire energy lasers to freeze opponents. The Hunter wears the crown. Freeze players, rescue frozen teammates, build your score and survive the round.</p><div class="dfMPFeatures"><div class="dfMPFeature"><b>⚡ LASER BEAMS</b><small>Server-synced shots</small></div><div class="dfMPFeature"><b>❄ FREEZE TAG</b><small>5-second freezes</small></div><div class="dfMPFeature"><b>👑 HUNTER</b><small>Pass the crown</small></div><div class="dfMPFeature"><b>🛟 RESCUE</b><small>Thaw nearby players</small></div><div class="dfMPFeature"><b>🌌 MASSIVE ARENA</b><small>Neon battlefield</small></div><div class="dfMPFeature"><b>🏆 SCORE</b><small>Highest freeze count</small></div></div><input id="dfMPName" class="dfMPInput" maxlength="18" placeholder="Your player name" autocomplete="nickname"><input id="dfMPCode" class="dfMPInput" maxlength="6" placeholder="Room code (empty = create)"><div class="dfMPBtns"><button class="dfMPBtn primary" id="dfMPCreate">⚡ Create arena</button><button class="dfMPBtn" id="dfMPJoin">🚀 Join arena</button></div><div id="dfMPStatus" class="dfMPStatus"></div><div id="dfMPRoom" class="dfMPRoom"></div><div class="dfMPHint">WASD / arrows = move · Mouse = aim · Click / Space = laser · Walk to a frozen player to rescue them</div></div></div>
      <div id="dfMPHud"><div class="dfMPInfo" id="dfMPInfo">Connect to the arena.</div><div class="dfMPTouch"><button class="empty">•</button><button id="dfMPUp">▲</button><button class="empty">•</button><button id="dfMPLeft">◀</button><button class="empty">•</button><button id="dfMPRight">▶</button><button class="empty">•</button><button id="dfMPDown">▼</button></div></div>
    </div>`;
  document.body.appendChild(root);

  const canvas=root.querySelector('#dfMPCanvas'),ctx=canvas.getContext('2d'),lobby=root.querySelector('#dfMPLobby'),hud=root.querySelector('#dfMPHud'),status=root.querySelector('#dfMPStatus'),roomEl=root.querySelector('#dfMPRoom');
  let ws=null,room='',selfId='',players={},raf=0,last=0,keys={},touch={x:0,y:0},mouse={x:0,y:0,active:false},beams=[],fx=[],shotCooldown=0,roundEnds=0,roundOver=false;
  const server=()=>String(window.DEFGODQE_GAME_SERVER||DEFAULT_SERVER).replace(/\/$/,'');
  const W=()=>canvas.clientWidth,H=()=>canvas.clientHeight;
  function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);canvas.width=Math.max(1,r.width*d);canvas.height=Math.max(1,r.height*d);ctx.setTransform(d,0,0,d,0,0)}
  function setStatus(s){status.textContent=s}
  function open(){root.classList.add('open');lobby.style.display='flex';hud.style.display='none';resize();setStatus('');roomEl.textContent=''}
  function leave(){if(ws){try{ws.close()}catch{}}ws=null;players={};room='';selfId='';beams=[];fx=[];roundOver=false;cancelAnimationFrame(raf);hud.style.display='none';lobby.style.display='flex';roomEl.textContent=''}
  function close(){leave();root.classList.remove('open')}
  function connect(code,create){
    if(ws){try{ws.close()}catch{}}
    const name=(root.querySelector('#dfMPName').value.trim()||'player').slice(0,18);
    room=(code||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6);
    if(!create&&!room){setStatus('Enter a room code to join, or create a new arena.');return}
    setStatus('Connecting to the arena…');
    const url=server()+'?room='+encodeURIComponent(room)+(create?'&create=1':'')+'&name='+encodeURIComponent(name);
    try{ws=new WebSocket(url)}catch{setStatus('Could not open arena connection.');return}
    ws.onopen=()=>setStatus(create?'Arena created — loading the battlefield…':'Joining arena — loading players…');
    ws.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return}
      if(m.type==='welcome'){selfId=m.id;room=m.room;roundEnds=Number(m.roundEnds)||Date.now()+180000;roundOver=false;roomEl.textContent=room;players={};for(const p of m.players||[])players[p.id]=p;lobby.style.display='none';hud.style.display='flex';resize();last=performance.now();cancelAnimationFrame(raf);raf=requestAnimationFrame(loop);return}
      if(m.type==='state'){players={};for(const p of m.players||[])players[p.id]=p;roundEnds=Number(m.roundEnds)||roundEnds;roundOver=Boolean(m.roundOver);updateHud();return}
      if(m.type==='beam'){beams.push({shooter:m.from,x:m.x,y:m.y,angle:Number(m.angle)||0,range:Number(m.range)||.72,t:.16,hit:m.hit});if(m.hit)fx.push({id:m.hit,t:1,type:'hit'});return}
      if(m.type==='freeze'){fx.push({id:m.target,t:1.3,type:'freeze'});if(m.shooter===selfId) setStatus('DIRECT HIT! +1 FREEZE');return}
      if(m.type==='tag'){fx.push({id:m.to,t:1,type:'tag'});return}
      if(m.type==='thaw'){fx.push({id:m.target,t:1,type:'thaw'});return}
      if(m.type==='round_end'){roundOver=true;const w=m.winner;setStatus(w?`ROUND OVER — ${w.name} wins with ${w.score} freezes!`:'ROUND OVER');return}
      if(m.type==='error'){setStatus(m.message||'Arena error');if(m.close)leave()}
    };
    ws.onerror=()=>setStatus('Multiplayer server unavailable. Deploy the defgodqe-ai Worker, then try again.');
    ws.onclose=()=>{if(root.classList.contains('open')&&!roundOver){setStatus('Disconnected from arena.');hud.style.display='none';lobby.style.display='flex'}};
  }
  function updateHud(){const list=Object.values(players),me=players[selfId],now=Date.now();root.querySelector('#dfMPPlayers').textContent=list.length;root.querySelector('#dfMPFrozen').textContent=list.filter(p=>p.frozenUntil&&p.frozenUntil>now).length;const left=Math.max(0,Math.ceil((roundEnds-now)/1000));root.querySelector('#dfMPTime').textContent=Math.floor(left/60)+':'+String(left%60).padStart(2,'0');if(roundOver){root.querySelector('#dfMPInfo').textContent='🏆 ROUND OVER — reconnect to start a new round';return}if(!me){root.querySelector('#dfMPInfo').textContent='Connecting…';return}if(me.it){root.querySelector('#dfMPInfo').textContent='👑 YOU ARE THE HUNTER — tag or freeze them!';return}if(me.frozenUntil&&me.frozenUntil>now){root.querySelector('#dfMPInfo').textContent='❄ YOU ARE FROZEN — a player can rescue you!';return}const score=Number(me.score)||0;root.querySelector('#dfMPInfo').textContent=`⚡ SCORE ${score} — aim, fire and rescue frozen players`}
  function sendMove(){if(!ws||ws.readyState!==1||roundOver)return;let x=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0)+touch.x,y=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0)+touch.y;if(x||y){const n=Math.hypot(x,y)||1;ws.send(JSON.stringify({type:'move',x:x/n,y:y/n}))}}
  function shoot(){if(!ws||ws.readyState!==1||shotCooldown>0||roundOver)return;const p=players[selfId];if(!p||p.frozenUntil>Date.now())return;let angle=mouse.active?Math.atan2(mouse.y-H()/2,mouse.x-W()/2):0;ws.send(JSON.stringify({type:'shoot',angle}));shotCooldown=.35}
  function thawNearest(){if(!ws||ws.readyState!==1)return;const me=players[selfId];if(!me)return;let target=null,best=.1;for(const p of Object.values(players)){if(p.id===selfId||!p.frozenUntil||p.frozenUntil<=Date.now())continue;const d=Math.hypot(me.x-p.x,me.y-p.y);if(d<best){best=d;target=p}}if(target)ws.send(JSON.stringify({type:'thaw',targetId:target.id}))}
  function drawArena(t){const w=W(),h=H();ctx.fillStyle='#02050a';ctx.fillRect(0,0,w,h);const g=ctx.createRadialGradient(w*.5,h*.48,10,w*.5,h*.48,Math.max(w,h)*.72);g.addColorStop(0,'rgba(250,204,21,.09)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(250,204,21,.055)';ctx.lineWidth=1;for(let x=0;x<w;x+=38){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=38){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.strokeStyle='rgba(250,204,21,.22)';ctx.lineWidth=2;ctx.strokeRect(20,60,w-40,h-90);for(let i=0;i<12;i++){const a=t*.00035+i*.52,x=w*.5+Math.cos(a)*Math.min(w,h)*.35,y=h*.5+Math.sin(a)*Math.min(w,h)*.35;ctx.beginPath();ctx.arc(x,y,25+Math.sin(t*.002+i)*5,0,Math.PI*2);ctx.strokeStyle='rgba(250,204,21,.08)';ctx.stroke()}}
  function draw(t){drawArena(t);const w=W(),h=H(),now=Date.now();for(const b of beams){const p=players[b.shooter];if(!p)continue;const x=p.x*w,y=p.y*h,len=Math.max(w,h)*Number(b.range||.72)*.72,endX=x+Math.cos(b.angle)*len,endY=y+Math.sin(b.angle)*len;ctx.save();ctx.globalAlpha=Math.min(1,b.t/.06);ctx.strokeStyle='#fde047';ctx.shadowBlur=30;ctx.shadowColor='#facc15';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(endX,endY);ctx.stroke();ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(endX,endY);ctx.stroke();ctx.restore();b.t-=.016}
    beams=beams.filter(b=>b.t>0);
    for(const p of Object.values(players)){const x=p.x*w,y=p.y*h,frozen=p.frozenUntil&&p.frozenUntil>now,hunter=p.it;ctx.save();ctx.shadowBlur=hunter?42:28;ctx.shadowColor=hunter?'#facc15':frozen?'#60a5fa':'#fde047';ctx.beginPath();ctx.arc(x,y,hunter?18:15,0,Math.PI*2);ctx.fillStyle=hunter?'#fde047':frozen?'#60a5fa':'#fff';ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle=hunter?'#fff':'#facc15';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,hunter?29:23,0,Math.PI*2);ctx.stroke();if(hunter){ctx.font='900 17px system-ui';ctx.textAlign='center';ctx.fillStyle='#fde047';ctx.fillText('👑',x,y-35)}if(frozen){ctx.strokeStyle='#60a5fa';ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,30,0,Math.PI*2);ctx.stroke()}if(p.id===selfId){ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,36,0,Math.PI*2);ctx.stroke()}ctx.fillStyle='#fff';ctx.font='800 12px system-ui';ctx.textAlign='center';ctx.fillText(p.name||'player',x,y+44);if(Number(p.score)>0){ctx.fillStyle='#fde047';ctx.font='700 10px system-ui';ctx.fillText('FREEZES '+p.score,x,y+56)}ctx.restore()}
    for(const f of fx){const p=players[f.id];if(!p){f.t-=.04;continue}const x=p.x*w,y=p.y*h;ctx.save();ctx.globalAlpha=Math.max(0,f.t);ctx.strokeStyle=f.type==='thaw'?'#fde047':f.type==='tag'?'#fff':'#60a5fa';ctx.lineWidth=4;ctx.shadowBlur=24;ctx.shadowColor=ctx.strokeStyle;ctx.beginPath();ctx.arc(x,y,35+(1-f.t)*35,0,Math.PI*2);ctx.stroke();ctx.restore();f.t-=.035}fx=fx.filter(f=>f.t>0);}
  function loop(t){if(!root.classList.contains('open'))return;const dt=Math.min(.05,(t-last)/1000||.016);last=t;shotCooldown=Math.max(0,shotCooldown-dt);sendMove();draw(t);updateHud();raf=requestAnimationFrame(loop)}
  function touchButton(id,x,y){const b=root.querySelector(id);if(!b)return;const down=e=>{e.preventDefault();touch.x=x;touch.y=y};const up=e=>{e.preventDefault();if(touch.x===x&&touch.y===y){touch.x=0;touch.y=0}};b.addEventListener('pointerdown',down);b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);b.addEventListener('pointerleave',up)}
  root.querySelector('#dfMPCreate').addEventListener('click',()=>connect('',true));root.querySelector('#dfMPJoin').addEventListener('click',()=>connect(root.querySelector('#dfMPCode').value,false));root.querySelector('#dfMPClose').addEventListener('click',close);
  root.querySelector('#dfMPCode').addEventListener('keydown',e=>{if(e.key==='Enter')connect(root.querySelector('#dfMPCode').value,false)});
  root.querySelector('#dfMPName').addEventListener('keydown',e=>{if(e.key==='Enter')connect(root.querySelector('#dfMPCode').value||'',!root.querySelector('#dfMPCode').value)});
  window.addEventListener('resize',resize);
  window.addEventListener('keydown',e=>{if(!root.classList.contains('open')||['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;keys[e.key]=true;if(e.code==='Space'){e.preventDefault();shoot()}if(e.key==='e'||e.key==='E')thawNearest()});
  window.addEventListener('keyup',e=>{keys[e.key]=false});
  canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();mouse.x=e.clientX-r.left;mouse.y=e.clientY-r.top;mouse.active=true});canvas.addEventListener('pointerdown',e=>{if(e.button===0){const r=canvas.getBoundingClientRect();mouse.x=e.clientX-r.left;mouse.y=e.clientY-r.top;mouse.active=true;shoot()}});
  touchButton('#dfMPUp',0,-1);touchButton('#dfMPDown',0,1);touchButton('#dfMPLeft',-1,0);touchButton('#dfMPRight',1,0);
  window.defgodqeMultiplayer={open,close,leave,shoot,thaw:thawNearest};
})();
