/* defgodqe — NEON TAG: glowing laser freeze-tag arena */
(() => {
'use strict';
if(window.__defgodqeMultiplayerGame)return;
window.__defgodqeMultiplayerGame=true;
const DEFAULT_SERVER='wss://defgodqe-ai.defgodqe.workers.dev/game';
const css=`
#dfMP{position:fixed;inset:0;z-index:100100;background:rgba(1,3,8,.94);backdrop-filter:blur(20px);display:none;align-items:center;justify-content:center;padding:10px;color:#fff;font-family:Inter,system-ui,sans-serif}#dfMP.open{display:flex}#dfMPPanel{position:relative;width:min(1500px,99vw);height:min(900px,97vh);overflow:hidden;border:1px solid rgba(250,204,21,.42);border-radius:28px;background:#02050a;box-shadow:0 0 120px rgba(250,204,21,.13),0 30px 120px #000}
#dfMPCanvas{position:absolute;inset:0;width:100%;height:100%;touch-action:none}#dfMPTop{position:absolute;left:24px;right:65px;top:18px;z-index:5;display:flex;align-items:center;gap:16px;pointer-events:none}.dfMPTitle{font-size:18px;font-weight:950;letter-spacing:.12em;text-shadow:0 0 25px #facc15}.dfMPTitle span{color:#facc15}.dfMPStats{display:flex;gap:14px;color:#94a3b8;font-size:11px}.dfMPStats b{color:#fde047;font-size:18px}.dfMPBadge{padding:7px 10px;border:1px solid #facc1540;border-radius:999px;background:#facc150b;color:#fde047;font-weight:900}
#dfMPClose{position:absolute;right:13px;top:13px;z-index:20;width:42px;height:42px;border-radius:13px;border:1px solid #fff2;background:#080c14e8;color:#fff;font-size:24px;cursor:pointer}#dfMPLobby{position:absolute;inset:0;z-index:10;display:flex;align-items:center;justify-content:center;background:radial-gradient(circle at 50% 30%,#facc1520,#03060bf5 60%);padding:24px;box-sizing:border-box}.dfMPCard{width:min(620px,100%);padding:34px;border:1px solid #facc1538;border-radius:28px;background:linear-gradient(145deg,#0c111beF,#05080eee);box-shadow:0 25px 90px #000a}.dfMPCard h1{margin:0;font-size:58px;letter-spacing:-.06em}.dfMPCard h1 span{color:#facc15;text-shadow:0 0 35px #facc15}.dfMPCard p{color:#94a3b8;line-height:1.6}.dfMPFeatures{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:18px 0}.dfMPFeature{padding:12px;border:1px solid #fff1;border-radius:14px;background:#ffffff05}.dfMPFeature b{display:block;color:#fde047;font-size:12px}.dfMPFeature small{color:#64748b}.dfMPInput{width:100%;box-sizing:border-box;padding:14px;margin:6px 0;border-radius:13px;border:1px solid #fff2;background:#03060b;color:#fff;outline:0}.dfMPInput:focus{border-color:#facc1580;box-shadow:0 0 0 3px #facc1512}.dfMPBtns{display:flex;gap:9px;flex-wrap:wrap;margin-top:12px}.dfMPBtn{border:1px solid #fff2;background:#ffffff0b;color:#fff;border-radius:13px;padding:12px 17px;font-weight:850;cursor:pointer}.dfMPBtn.primary{background:#facc15;color:#111827;border-color:#facc15;box-shadow:0 0 28px #facc1530}.dfMPStatus{min-height:20px;color:#94a3b8;font-size:13px;margin-top:11px}.dfMPRoom{font-size:38px;letter-spacing:.2em;font-weight:950;color:#fde047;text-align:center;margin:14px 0;text-shadow:0 0 25px #facc15}.dfMPHint{font-size:11px;color:#64748b;text-align:center}
#dfMPHud{position:absolute;left:20px;right:20px;bottom:17px;z-index:5;display:none;align-items:flex-end;justify-content:space-between;gap:10px;pointer-events:none}.dfMPInfo{padding:10px 13px;border:1px solid #fff1;border-radius:14px;background:#05080dcc;backdrop-filter:blur(12px);color:#cbd5e1;font-size:12px;font-weight:800}.dfMPCross{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);font-size:30px;color:#fde047;text-shadow:0 0 18px #facc15;pointer-events:none}.dfMPTouch{display:none;grid-template-columns:repeat(3,54px);gap:6px;pointer-events:auto}.dfMPTouch button{width:54px;height:50px;border-radius:14px;border:1px solid #facc1545;background:#080c14dd;color:#fde047;font-size:20px;touch-action:none}.dfMPTouch .empty{visibility:hidden}
@media(max-width:700px){#dfMP{padding:0}#dfMPPanel{width:100vw;height:100dvh;border-radius:0}.dfMPCard{padding:22px}.dfMPCard h1{font-size:40px}.dfMPFeatures{grid-template-columns:1fr 1fr}.dfMPTouch{display:grid}}
`;
const style=document.createElement('style');style.textContent=css;document.head.appendChild(style);
const root=document.createElement('div');root.id='dfMP';root.innerHTML=`<div id="dfMPPanel"><canvas id="dfMPCanvas"></canvas><div id="dfMPTop"><div class="dfMPTitle">NEON <span>TAG</span></div><div class="dfMPBadge">FREEZE ARENA</div><div class="dfMPStats">PLAYERS <b id="dfMPPlayers">0</b></div><div class="dfMPStats">FROZEN <b id="dfMPFrozen">0</b></div></div><button id="dfMPClose">×</button><div id="dfMPLobby"><div class="dfMPCard"><h1>NEON <span>TAG</span></h1><p>Enter the massive glowing arena. Sprint, dodge and fire energy beams to freeze opponents. The first player is the Hunter. Freeze the Hunter and the crown moves to the next player. Up to 8 players per room.</p><div class="dfMPFeatures"><div class="dfMPFeature"><b>⚡ LASER BEAMS</b><small>Fast energy shots</small></div><div class="dfMPFeature"><b>❄ FREEZE TAG</b><small>5-second freezes</small></div><div class="dfMPFeature"><b>👑 HUNTER</b><small>Pass the crown</small></div><div class="dfMPFeature"><b>💥 COMBOS</b><small>Score every freeze</small></div><div class="dfMPFeature"><b>🌌 MASSIVE ARENA</b><small>Glow grid battlefield</small></div><div class="dfMPFeature"><b>🏆 SCORE</b><small>Top the room</small></div></div><input id="dfMPName" class="dfMPInput" maxlength="20" placeholder="Your player name"><input id="dfMPCode" class="dfMPInput" maxlength="6" placeholder="Room code (empty = create)"><div class="dfMPBtns"><button class="dfMPBtn primary" id="dfMPCreate">⚡ Create arena</button><button class="dfMPBtn" id="dfMPJoin">🚀 Join arena</button></div><div id="dfMPStatus" class="dfMPStatus"></div><div id="dfMPRoom" class="dfMPRoom"></div><div class="dfMPHint">WASD / arrows = move · Mouse = aim · Click / Space = laser · Mobile buttons = move</div></div></div><div id="dfMPHud"><div class="dfMPInfo" id="dfMPInfo">Find the Hunter.</div><div class="dfMPTouch"><button class="empty">•</button><button id="dfMPUp">▲</button><button class="empty">•</button><button id="dfMPLeft">◀</button><button class="empty">•</button><button id="dfMPRight">▶</button><button class="empty">•</button><button id="dfMPDown">▼</button></div></div><div class="dfMPCross">+</div></div>`;document.body.appendChild(root);
const canvas=root.querySelector('#dfMPCanvas'),ctx=canvas.getContext('2d'),lobby=root.querySelector('#dfMPLobby'),status=root.querySelector('#dfMPStatus'),roomEl=root.querySelector('#dfMPRoom');
let ws=null,room='',players={},selfId='',raf=0,last=0,keys={},touch={x:0,y:0},mouse={x:0,y:0,active:false},beams=[],freezeFx=[],shotCooldown=0,shots=0,score=0;
const server=()=>String(window.DEFGODQE_GAME_SERVER||DEFAULT_SERVER).replace(/\/$/,'');const resize=()=>{const r=canvas.getBoundingClientRect(),d=Math.min(2,devicePixelRatio||1);canvas.width=Math.max(1,r.width*d);canvas.height=Math.max(1,r.height*d);ctx.setTransform(d,0,0,d,0,0)};const W=()=>canvas.getBoundingClientRect().width,H=()=>canvas.getBoundingClientRect().height;
function setStatus(s){status.textContent=s}function open(){root.classList.add('open');lobby.style.display='flex';resize();setStatus('');roomEl.textContent=''}function leave(){if(ws){try{ws.close()}catch{}}ws=null;players={};room='';selfId='';beams=[];freezeFx=[];cancelAnimationFrame(raf);lobby.style.display='flex';root.querySelector('#dfMPHud').style.display='none';roomEl.textContent=''}function close(){leave();root.classList.remove('open')}
function connect(code,create){const name=(root.querySelector('#dfMPName').value.trim()||'player').slice(0,20);room=(code||'').toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6);setStatus('Connecting to the arena…');const url=server()+'?room='+encodeURIComponent(room)+(create?'&create=1':'')+'&name='+encodeURIComponent(name);try{ws=new WebSocket(url)}catch{setStatus('Could not open arena connection.');return}ws.onopen=()=>{setStatus(create?'Arena created — share the code below!':'Joined arena — loading players…')};ws.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return}if(m.type==='welcome'){selfId=m.id;room=m.room;roomEl.textContent=room;players={};for(const p of m.players||[])players[p.id]=p;lobby.style.display='none';root.querySelector('#dfMPHud').style.display='flex';resize();last=performance.now();raf=requestAnimationFrame(loop);return}if(m.type==='state'){players={};for(const p of m.players||[])players[p.id]=p;const list=Object.values(players);root.querySelector('#dfMPPlayers').textContent=list.length;root.querySelector('#dfMPFrozen').textContent=list.filter(p=>p.frozenUntil&&p.frozenUntil>Date.now()).length;const me=players[selfId];root.querySelector('#dfMPInfo').textContent=me?.it?'👑 YOU ARE THE HUNTER — FREEZE THEM!':me?.frozenUntil>Date.now()?'❄ FROZEN — wait for the thaw!':'⚡ Aim and freeze the Hunter!'}if(m.type==='beam'){beams.push({...m,t:0.18});if(m.target){freezeFx.push({id:m.target,t:1})}}if(m.type==='freeze'){if(m.by===selfId){score++;root.querySelector('#dfMPInfo').textContent='❄ DIRECT HIT! +1 FREEZE'}freezeFx.push({id:m.target,t:1.2})}if(m.type==='error'){setStatus(m.message||'Arena error');if(m.close)leave()}if(m.type==='room'){room=m.room;roomEl.textContent=room}};ws.onerror=()=>setStatus('Multiplayer server unavailable. Check the game Worker deployment.');ws.onclose=()=>{if(root.classList.contains('open')){setStatus('Disconnected from arena.');root.querySelector('#dfMPHud').style.display='none';lobby.style.display='flex'}}}
function sendMove(){if(!ws||ws.readyState!==1)return;let x=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0)+touch.x,y=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0)+touch.y;if(x||y){const n=Math.hypot(x,y)||1;ws.send(JSON.stringify({type:'move',x:x/n,y:y/n}))}}
function shoot(){if(!ws||ws.readyState!==1||shotCooldown>0)return;const p=players[selfId];if(!p||p.frozenUntil>Date.now())return;let angle=mouse.active?Math.atan2(mouse.y-H()/2,mouse.x-W()/2):0;ws.send(JSON.stringify({type:'shoot',angle}));shotCooldown=.26;shots++}
function drawArena(t){const w=W(),h=H();ctx.fillStyle='#02050a';ctx.fillRect(0,0,w,h);const g=ctx.createRadialGradient(w*.5,h*.5,20,w*.5,h*.5,Math.max(w,h)*.75);g.addColorStop(0,'rgba(250,204,21,.08)');g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);ctx.strokeStyle='rgba(250,204,21,.055)';ctx.lineWidth=1;for(let x=0;x<w;x+=38){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=38){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}ctx.strokeStyle='rgba(250,204,21,.18)';ctx.lineWidth=2;ctx.strokeRect(20,60,w-40,h-90);for(let i=0;i<9;i++){const x=(i%3)*w/3+w/6,y=Math.floor(i/3)*h/3+h/5;ctx.beginPath();ctx.arc(x,y,42+Math.sin(t*.001+i)*5,0,Math.PI*2);ctx.strokeStyle='rgba(250,204,21,.035)';ctx.stroke()}}
function draw(t){drawArena(t);const w=W(),h=H();for(const b of beams){const p=players[b.shooter];if(!p)continue;const x=p.x*w,y=p.y*h,dx=Math.cos(b.angle),dy=Math.sin(b.angle);const endX=x+dx*Math.max(w,h)*.42,endY=y+dy*Math.max(w,h)*.42;ctx.save();ctx.globalAlpha=Math.min(1,b.t/.08);ctx.strokeStyle='#fde047';ctx.shadowBlur=25;ctx.shadowColor='#facc15';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(endX,endY);ctx.stroke();ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(endX,endY);ctx.stroke();ctx.restore()}
for(const p of Object.values(players)){const x=p.x*w,y=p.y*h,frozen=p.frozenUntil&&p.frozenUntil>Date.now();ctx.save();const hunter=p.it;ctx.shadowBlur=hunter?40:24;ctx.shadowColor=hunter?'#facc15':frozen?'#60a5fa':'#fde047';ctx.beginPath();ctx.arc(x,y,hunter?18:15,0,Math.PI*2);ctx.fillStyle=hunter?'#fde047':frozen?'#60a5fa':'#fff';ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle=hunter?'#fff':'#facc15';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,hunter?28:22,0,Math.PI*2);ctx.stroke();if(hunter){ctx.fillStyle='#fde047';ctx.font='900 16px Inter';ctx.textAlign='center';ctx.fillText('👑',x,y-34)}if(frozen){ctx.strokeStyle='#60a5fa';ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,29,0,Math.PI*2);ctx.stroke()}if(p.id===selfId){ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(x,y,35,0,Math.PI*2);ctx.stroke()}ctx.fillStyle='#fff';ctx.font='800 12px Inter,system-ui';ctx.textAlign='center';ctx.fillText(p.name||'player',x,y+43);if(Number(p.score)>0){ctx.fillStyle='#fde047';ctx.font='700 10px Inter';ctx.fillText('+'+p.score,x,y+55)}ctx.restore()}
for(const f of freezeFx){const p=players[f.id];if(!p)continue;const x=p.x*w,y=p.y*h;ctx.save();ctx.globalAlpha=Math.max(0,f.t);ctx.strokeStyle='#93c5fd';ctx.lineWidth=4;ctx.shadowBlur=30;ctx.shadowColor='#60a5fa';for(let i=0;i<6;i++){ctx.beginPath();ctx.moveTo(x+Math.cos(i)*12,y+Math.sin(i)*12);ctx.lineTo(x+Math.cos(i+.5)*42,y+Math.sin(i+.5)*42);ctx.stroke()}ctx.restore()}}
function loop(t){if(!root.classList.contains('open')||!ws)return;const dt=Math.min(.05,(t-last)/1000);last=t;shotCooldown=Math.max(0,shotCooldown-dt);sendMove();for(const b of beams)b.t-=dt;beams=beams.filter(b=>b.t>0);for(const f of freezeFx)f.t-=dt;freezeFx=freezeFx.filter(f=>f.t>0);draw(t);raf=requestAnimationFrame(loop)}
function bindTouch(id,axis,val){const b=root.querySelector(id),down=e=>{e.preventDefault();touch[axis]=val},up=e=>{e.preventDefault();if(touch[axis]===val)touch[axis]=0};b.addEventListener('pointerdown',down);b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up);b.addEventListener('pointerleave',up)}
bindTouch('#dfMPUp','y',-1);bindTouch('#dfMPDown','y',1);bindTouch('#dfMPLeft','x',-1);bindTouch('#dfMPRight','x',1);
root.querySelector('#dfMPCreate').onclick=()=>connect('',true);root.querySelector('#dfMPJoin').onclick=()=>{const c=root.querySelector('#dfMPCode').value.trim();if(c.length<4)return setStatus('Enter a room code.');connect(c,false)};root.querySelector('#dfMPClose').onclick=close;
canvas.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();mouse.x=e.clientX-r.left;mouse.y=e.clientY-r.top;mouse.active=true});canvas.addEventListener('pointerleave',()=>mouse.active=false);canvas.addEventListener('pointerdown',e=>{if(e.button===0){e.preventDefault();shoot()}});window.addEventListener('keydown',e=>{keys[e.key]=true;if(e.code==='Space'){e.preventDefault();shoot()}if(e.key==='Escape'&&root.classList.contains('open'))leave()});window.addEventListener('keyup',e=>{keys[e.key]=false});window.addEventListener('resize',resize);
window.defgodqeMultiplayer={open,close,leave};const launcher=document.createElement('button');launcher.id='dfMultiplayerLaunch';launcher.type='button';launcher.textContent='⚡ NEON TAG';launcher.title='Enter the multiplayer freeze-tag laser arena';launcher.style.cssText='position:fixed;right:18px;bottom:18px;z-index:99990;border:1px solid rgba(250,204,21,.45);background:linear-gradient(145deg,rgba(250,204,21,.15),rgba(10,14,22,.96));color:#fde047;border-radius:14px;padding:11px 15px;font:900 13px Inter,system-ui,sans-serif;box-shadow:0 0 30px #facc1515,0 12px 35px #0008;cursor:pointer';launcher.onclick=open;document.body.appendChild(launcher);
})();
